const mobileMenuButton = document.getElementById('mobile-menu-button');
const mobileMenu = document.getElementById('mobile-menu');
mobileMenuButton.addEventListener('click', () => {
    mobileMenu.classList.toggle('hidden');
});
// Carousel Script
const carouselItems = document.querySelectorAll('.carousel-item');
const indicators = document.querySelectorAll('#indicators .indicator');
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');
let currentIndex = 0;
let intervalId;
function updateCarousel() {
    carouselItems.forEach((item, index) => {
        item.classList.toggle('active', index === currentIndex);
    });
    indicators.forEach((indicator, index) => {
        indicator.classList.toggle('active-indicator', index === currentIndex);
        indicator.classList.toggle('opacity-100', index === currentIndex);
        indicator.classList.toggle('opacity-50', index !== currentIndex);
    });
}
function showNext() {
    currentIndex = (currentIndex + 1) % carouselItems.length;
    updateCarousel();
}
function showPrev() {
    currentIndex = (currentIndex - 1 + carouselItems.length) % carouselItems.length;
    updateCarousel();
}
function startAutoplay() {
    intervalId = setInterval(showNext, 5000); // Change slide every 5 seconds
}
function stopAutoplay() {
    clearInterval(intervalId);
}
nextBtn.addEventListener('click', () => {
    showNext();
    stopAutoplay();
    startAutoplay();
});
prevBtn.addEventListener('click', () => {
    showPrev();
    stopAutoplay();
    startAutoplay();
});
indicators.forEach((indicator, index) => {
    indicator.addEventListener('click', () => {
        currentIndex = index;
        updateCarousel();
        stopAutoplay();
        startAutoplay();
    });
});

updateCarousel();
startAutoplay();

document.addEventListener('DOMContentLoaded', () => {
    const links = document.querySelectorAll('a[href]');

    links.forEach(link => {
        const href = link.getAttribute('href');
        if (href.startsWith('#')) {
            return;
        }
        const isInternal = (link.hostname === window.location.hostname || link.hostname === '');

        if (isInternal) {
            link.addEventListener('click', (event) => {
                event.preventDefault();
                document.body.classList.add('page-exit');
                setTimeout(() => {
                    window.location.href = href;
                }, 300);
            });
        }
    });
});
/**
* Lógica para a busca de representantes por Estado + Município.
* Usa Select2 para um dropdown de municípios pesquisável.
*
* ATUALIZAÇÃO: Adicionados dados completos do RS (Representações Bortolan).
*/

// --- 1. BASE DE DADOS (Representantes, Mapeamento de Municípios, Lista Completa) ---

/**
 * Mapeamento dos representantes (IDs e Detalhes).
 */
const REPRESENTANTES_MAP = {
    // --- Representantes do Paraná (Mantidos) ---
    'rep_pr_sergio': {
        nome: 'Sergio Siemieniaco (PR)',
        telefone: '(42) 9921-4872',
        email: 'sergiosiemieniaco@hotmail.com',
    },
    'rep_pr_ricardo': {
        nome: 'Ricardo Veronese (PR)',
        telefone: '(45) 9979-9301',
        email: 'ricardo.veronese@gmail.com',
    },
    'rep_pr_jefferson': {
        nome: 'Jefferson Scussiatto (PR)',
        telefone: '(49) 9902-6000',
        email: 'tidyvendas@gmail.com',
    },
    'rep_pr_tiago': {
        nome: 'Tiago Costella (PR)',
        telefone: '(49) 9821-1224',
        email: 'tidyvendas@gmail.com',
    },

    // --- Representantes de Santa Catarina (Exemplo) ---
    'rep_sc_ana': {
        nome: 'Ana (SC)',
        telefone: '(48) 99999-0005',
        email: 'ana.rep@email.com',
    },

    // --- Representantes do Rio Grande do Sul (ATUALIZADO) ---
    'rep_rs_bortolan': {
        nome: 'Representações Bortolan (RS)',
        telefone: '(54) 3361-1541',
        email: 'repres.bortolan@yahoo.com.br',
    }
};

/**
 * Mapeamento APENAS dos Municípios QUE TÊM REPRESENTANTE.
 * Usado para a lógica de busca.
 */
const MUNICIPIOS_MAP = {
    // --- PARANÁ (PR) ---
    // (Mantida a lista anterior do PR)
    'abatiá (pr)': 'rep_pr_sergio',
    'altamira do paraná (pr)': 'rep_pr_ricardo',
    'altônia (pr)': 'rep_pr_ricardo',
    'alvorada do sul (pr)': 'rep_pr_sergio',
    'ampere (pr)': 'rep_pr_jefferson',
    'anahy (pr)': 'rep_pr_ricardo',
    'andira (pr)': 'rep_pr_sergio',
    'apucarana (pr)': 'rep_pr_sergio',
    'arapongas (pr)': 'rep_pr_sergio',
    'arapoti (pr)': 'rep_pr_sergio',
    'arapuã (pr)': 'rep_pr_sergio',
    'ariranha do ivaí (pr)': 'rep_pr_sergio',
    'assaí (pr)': 'rep_pr_sergio',
    'assis chateaubriand (pr)': 'rep_pr_ricardo',
    'bandeirantes (pr)': 'rep_pr_sergio',
    'barra do jacare (pr)': 'rep_pr_sergio',
    'barracão (pr)': 'rep_pr_jefferson',
    'bela vista da caroba (pr)': 'rep_pr_jefferson',
    'bela vista do paraíso (pr)': 'rep_pr_sergio',
    'bituruna (pr)': 'rep_pr_tiago',
    'boa esperança do iguaçú (pr)': 'rep_pr_jefferson',
    'boa ventura do são roque (pr)': 'rep_pr_sergio',
    'boa vista da aparecida (pr)': 'rep_pr_ricardo',
    'bom jesus do sul (pr)': 'rep_pr_jefferson',
    'bom sucesso do sul (pr)': 'rep_pr_jefferson',
    'borrazópolis (pr)': 'rep_pr_sergio',
    'braganey (pr)': 'rep_pr_ricardo',
    'cafelandia (pr)': 'rep_pr_ricardo',
    'califórnia (pr)': 'rep_pr_sergio',
    'cambará (pr)': 'rep_pr_sergio',
    'cambé (pr)': 'rep_pr_sergio',
    'campina da lagoa (pr)': 'rep_pr_ricardo',
    'campina do simao (pr)': 'rep_pr_sergio',
    'campo bonito (pr)': 'rep_pr_ricardo',
    'campo mourão (pr)': 'rep_pr_ricardo',
    'cândido de abreu (pr)': 'rep_pr_sergio',
    'candoi (pr)': 'rep_pr_sergio',
    'cantagalo (pr)': 'rep_pr_sergio',
    'capanema (pr)': 'rep_pr_jefferson',
    'capitão leônidas marques (pr)': 'rep_pr_ricardo',
    'carambeí (pr)': 'rep_pr_sergio',
    'carlópolis (pr)': 'rep_pr_sergio',
    'cascavel (pr)': 'rep_pr_ricardo',
    'castro (pr)': 'rep_pr_sergio',
    'catanduvas (pr)': 'rep_pr_ricardo',
    'céu azul (pr)': 'rep_pr_ricardo',
    'chopinzinho (pr)': 'rep_pr_jefferson',
    'clevelândia (pr)': 'rep_pr_jefferson',
    'congonhinhas (pr)': 'rep_pr_sergio',
    'conselheiro mairinck (pr)': 'rep_pr_sergio',
    'corbélia (pr)': 'rep_pr_ricardo',
    'cornélio procopio (pr)': 'rep_pr_sergio',
    'coronel domingos soares (pr)': 'rep_pr_jefferson',
    'coronel vivida (pr)': 'rep_pr_jefferson',
    'cruz machado (pr)': 'rep_pr_tiago',
    'cruzeiro do iguaçú (pr)': 'rep_pr_jefferson',
    'cruzmaltina (pr)': 'rep_pr_sergio',
    'curiúva (pr)': 'rep_pr_sergio',
    'diamante do oeste (pr)': 'rep_pr_ricardo',
    'diamante do sul (pr)': 'rep_pr_ricardo',
    'dois vizinhos (pr)': 'rep_pr_jefferson',
    'éneas marques (pr)': 'rep_pr_jefferson',
    'entre rios do oeste (pr)': 'rep_pr_ricardo',
    'espigão alto do iguaçu (pr)': 'rep_pr_ricardo',
    'faxinal (pr)': 'rep_pr_sergio',
    'fernandes pinheiro (pr)': 'rep_pr_sergio',
    'figueira (pr)': 'rep_pr_sergio',
    'flor da serra do sul (pr)': 'rep_pr_jefferson',
    'foz do iguaçu (pr)': 'rep_pr_ricardo',
    'foz do jordão (pr)': 'rep_pr_sergio',
    'francisco beltrão (pr)': 'rep_pr_jefferson',
    'general carneiro (pr)': 'rep_pr_tiago',
    'goioxím (pr)': 'rep_pr_sergio',
    'grandes rios (pr)': 'rep_pr_sergio',
    'guaíra (pr)': 'rep_pr_ricardo',
    'guamiranga (pr)': 'rep_pr_sergio',
    'guapirama (pr)': 'rep_pr_sergio',
    'guaraniaçu (pr)': 'rep_pr_ricardo',
    'guarapuava (pr)': 'rep_pr_sergio',
    'honório serpa (pr)': 'rep_pr_jefferson',
    'ibaiti (pr)': 'rep_pr_sergio',
    'ibema (pr)': 'rep_pr_ricardo',
    'ibiporã (pr)': 'rep_pr_sergio',
    'iguatu (pr)': 'rep_pr_ricardo',
    'imbaú (pr)': 'rep_pr_sergio',
    'imbituva (pr)': 'rep_pr_sergio',
    'inácio martins (pr)': 'rep_pr_sergio',
    'ipiranga (pr)': 'rep_pr_sergio',
    'iracema do oeste (pr)': 'rep_pr_ricardo',
    'irati (pr)': 'rep_pr_sergio',
    'itaipulândia (pr)': 'rep_pr_ricardo',
    'itambaracá (pr)': 'rep_pr_sergio',
    'itapejara do oeste (pr)': 'rep_pr_jefferson',
    'ivaí (pr)': 'rep_pr_sergio',
    'ivaiporã (pr)': 'rep_pr_sergio',
    'jaboti (pr)': 'rep_pr_sergio',
    'jacarezinho (pr)': 'rep_pr_sergio',
    'jaguariaíva (pr)': 'rep_pr_sergio',
    'japira (pr)': 'rep_pr_sergio',
    'japurá (pr)': 'rep_pr_ricardo',
    'jardim alegre (pr)': 'rep_pr_sergio',
    'jataizinho (pr)': 'rep_pr_sergio',
    'joaquim távora (pr)': 'rep_pr_sergio',
    'jundiaí do sul (pr)': 'rep_pr_sergio',
    'laranjal (pr)': 'rep_pr_ricardo',
    'laranjeiras do sul (pr)': 'rep_pr_sergio',
    'leópolis (pr)': 'rep_pr_sergio',
    'lidianópolis (pr)': 'rep_pr_sergio',
    'lindoeste (pr)': 'rep_pr_ricardo',
    'londrina (pr)': 'rep_pr_sergio',
    'mallet (pr)': 'rep_pr_sergio',
    'manfrinópolis (pr)': 'rep_pr_jefferson',
    'mangueirinha (pr)': 'rep_pr_jefferson',
    'manoel ribas (pr)': 'rep_pr_sergio',
    'marechal candido rondon (pr)': 'rep_pr_ricardo',
    'marilândia do sul (pr)': 'rep_pr_sergio',
    'mariluz (pr)': 'rep_pr_ricardo',
    'mariópolis (pr)': 'rep_pr_jefferson',
    'maripá (pr)': 'rep_pr_ricardo',
    'marmeleiro (pr)': 'rep_pr_jefferson',
    'marquinho (pr)': 'rep_pr_sergio',
    'matelândia (pr)': 'rep_pr_ricardo',
    'mauá da serra (pr)': 'rep_pr_sergio',
    'medianeira (pr)': 'rep_pr_ricardo',
    'mercedes (pr)': 'rep_pr_ricardo',
    'missal (pr)': 'rep_pr_ricardo',
    'moreira sales (pr)': 'rep_pr_ricardo',
    'nova américa da colina (pr)': 'rep_pr_sergio',
    'nova aurora (pr)': 'rep_pr_ricardo',
    'nova cantu (pr)': 'rep_pr_ricardo',
    'nova esperança do sudoeste (pr)': 'rep_pr_jefferson',
    'nova fátima (pr)': 'rep_pr_sergio',
    'nova laranjeiras (pr)': 'rep_pr_ricardo',
    'nova prata do iguaçú (pr)': 'rep_pr_jefferson',
    'nova santa bárbara (pr)': 'rep_pr_sergio',
    'nova santa rosa (pr)': 'rep_pr_ricardo',
    'ortigueira (pr)': 'rep_pr_sergio',
    'ouro verde do oeste (pr)': 'rep_pr_ricardo',
    'palmas (pr)': 'rep_pr_jefferson',
    'palmeira (pr)': 'rep_pr_sergio',
    'palmital (pr)': 'rep_pr_ricardo',
    'palotina (pr)': 'rep_pr_ricardo',
    'pato bragado (pr)': 'rep_pr_ricardo',
    'pato branco (pr)': 'rep_pr_jefferson',
    'paula freitas (pr)': 'rep_pr_tiago',
    'paulo frontin (pr)': 'rep_pr_tiago',
    'pérola do oeste (pr)': 'rep_pr_jefferson',
    'pinhalão (pr)': 'rep_pr_sergio',
    'pinhão (pr)': 'rep_pr_sergio',
    'pinhao de são bento (pr)': 'rep_pr_jefferson',
    'piraí do sul (pr)': 'rep_pr_sergio',
    'pitanga (pr)': 'rep_pr_sergio',
    'planaltina (pr)': 'rep_pr_jefferson',
    'ponta grossa (pr)': 'rep_pr_sergio',
    'porto barreiro (pr)': 'rep_pr_sergio',
    'porto vitória (pr)': 'rep_pr_tiago',
    'pranchita (pr)': 'rep_pr_jefferson',
    'primeiro de maio (pr)': 'rep_pr_sergio',
    'prudentópolis (pr)': 'rep_pr_sergio',
    'quatingá (pr)': 'rep_pr_sergio',
    'quatro pontes (pr)': 'rep_pr_ricardo',
    'quedas do iguaçu (pr)': 'rep_pr_ricardo',
    'ramilândia (pr)': 'rep_pr_ricardo',
    'rancho alegre (pr)': 'rep_pr_sergio',
    'realeza (pr)': 'rep_pr_jefferson',
    'rebouças (pr)': 'rep_pr_sergio',
    'renascença (pr)': 'rep_pr_jefferson',
    'reserva (pr)': 'rep_pr_sergio',
    'reserva do iguaçu (pr)': 'rep_pr_jefferson',
    'ribeirão claro (pr)': 'rep_pr_sergio',
    'ribeirão do pinhal (pr)': 'rep_pr_sergio',
    'rio azul (pr)': 'rep_pr_sergio',
    'rio bom (pr)': 'rep_pr_sergio',
    'rio bonito do iguaçu (pr)': 'rep_pr_sergio',
    'rio branco do ivaí (pr)': 'rep_pr_sergio',
    'rolândia (pr)': 'rep_pr_sergio',
    'rosário do ivaí (pr)': 'rep_pr_sergio',
    'salgado filho (pr)': 'rep_pr_jefferson',
    'salto do itararé (pr)': 'rep_pr_sergio',
    'salto do lontra (pr)': 'rep_pr_jefferson',
    'santa amelia (pr)': 'rep_pr_sergio',
    'santa cecília do pavão (pr)': 'rep_pr_sergio',
    'santa helena (pr)': 'rep_pr_ricardo',
    'santa izabel do oeste (pr)': 'rep_pr_jefferson',
    'santa lucia (pr)': 'rep_pr_ricardo',
    'santa maria do oeste (pr)': 'rep_pr_sergio',
    'santa mariana (pr)': 'rep_pr_sergio',
    'santa tereza do oeste (pr)': 'rep_pr_ricardo',
    'santa terezinha de itaipu (pr)': 'rep_pr_ricardo',
    'santana do itararé (pr)': 'rep_pr_sergio',
    'santo antonio da platina (pr)': 'rep_pr_sergio',
    'santo antonio do paraíso (pr)': 'rep_pr_sergio',
    'santo antônio do sudoeste (pr)': 'rep_pr_jefferson',
    'são jerônimo da serra (pr)': 'rep_pr_sergio',
    'são joão do triunfo (pr)': 'rep_pr_sergio',
    'são jorge do oeste (pr)': 'rep_pr_jefferson',
    'são josé da boa vista (pr)': 'rep_pr_sergio',
    'sao jose das palmeiras (pr)': 'rep_pr_ricardo',
    'são mateus do sul (pr)': 'rep_pr_sergio',
    'são miguel do iguaçu (pr)': 'rep_pr_ricardo',
    'são pedro do iguaçu (pr)': 'rep_pr_ricardo',
    'são sebastião da amoreira (pr)': 'rep_pr_sergio',
    'sapopema (pr)': 'rep_pr_sergio',
    'saudades do iguaçu (pr)': 'rep_pr_jefferson',
    'sengés (pr)': 'rep_pr_sergio',
    'serranópolis do iguaçu (pr)': 'rep_pr_ricardo',
    'sertaneja (pr)': 'rep_pr_sergio',
    'sertanópolis (pr)': 'rep_pr_sergio',
    'siqueira campos (pr)': 'rep_pr_sergio',
    'sulinas (pr)': 'rep_pr_jefferson',
    'tamarana (pr)': 'rep_pr_sergio',
    'teixeira soares (pr)': 'rep_pr_sergio',
    'telêmaco borba (pr)': 'rep_pr_sergio',
    'terra roxa (pr)': 'rep_pr_ricardo',
    'tibagi (pr)': 'rep_pr_sergio',
    'toledo (pr)': 'rep_pr_ricardo',
    'tomazina (pr)': 'rep_pr_sergio',
    'três barras do paraná (pr)': 'rep_pr_ricardo',
    'tupassi (pr)': 'rep_pr_ricardo',
    'turvo (pr)': 'rep_pr_sergio',
    'ubiratã (pr)': 'rep_pr_ricardo',
    'umuarama (pr)': 'rep_pr_ricardo',
    'união da vitória (pr)': 'rep_pr_tiago',
    'uraí (pr)': 'rep_pr_sergio',
    'ventania (pr)': 'rep_pr_sergio',
    'veracruz do oeste (pr)': 'rep_pr_ricardo',
    'verê (pr)': 'rep_pr_jefferson',
    'virmond (pr)': 'rep_pr_sergio',
    'vitorino (pr)': 'rep_pr_jefferson',
    'wenceslau bráz (pr)': 'rep_pr_sergio',

    // --- Santa Catarina (SC) ---
    'abdon batista (sc)': 'rep_pr_tiago',
    'abelardo luz (sc)': 'rep_pr_jefferson',
    'agrolândia (sc)': 'rep_pr_tiago',
    'agronômica (sc)': 'rep_pr_tiago',
    'água doce (sc)': 'rep_pr_tiago',
    'aguas chapeco (sc)': 'rep_pr_jefferson',
    'aguas frias (sc)': 'rep_pr_jefferson',
    'águas mornas (sc)': 'rep_pr_tiago',
    'alfredo wagner (sc)': 'rep_pr_tiago',
    'alto bela vista (sc)': 'rep_pr_jefferson',
    'anchieta (sc)': 'rep_pr_jefferson',
    'angelina (sc)': 'rep_pr_tiago',
    'anita garibaldi (sc)': 'rep_pr_tiago',
    'anitápolis (sc)': 'rep_pr_tiago',
    'antônio carlos (sc)': 'rep_pr_tiago',
    'apiúna (sc)': 'rep_pr_tiago',
    'arabuta (sc)': 'rep_pr_jefferson',
    'araquari (sc)': 'rep_pr_tiago',
    'araranguá (sc)': 'rep_pr_tiago',
    'armazém (sc)': 'rep_pr_tiago',
    'arroio trinta (sc)': 'rep_pr_tiago',
    'arvoredo (sc)': 'rep_pr_jefferson',
    'ascurra (sc)': 'rep_pr_tiago',
    'atalanta (sc)': 'rep_pr_tiago',
    'aurora (sc)': 'rep_pr_tiago',
    'balneário arroio do silva (sc)': 'rep_pr_tiago',
    'balneário barra do sul (sc)': 'rep_pr_tiago',
    'balneário camboriú (sc)': 'rep_pr_tiago',
    'balneário gaivota (sc)': 'rep_pr_tiago',
    'balneário rincão (sc)': 'rep_pr_tiago',
    'bandeirante (sc)': 'rep_pr_jefferson',
    'barra bonita (sc)': 'rep_pr_jefferson',
    'barra velha (sc)': 'rep_pr_tiago',
    'bela vista do toldo (sc)': 'rep_pr_tiago',
    'belmonte (sc)': 'rep_pr_jefferson',
    'benedito novo (sc)': 'rep_pr_tiago',
    'biguaçu (sc)': 'rep_pr_tiago',
    'blumenau (sc)': 'rep_pr_tiago',
    'bocaina do sul (sc)': 'rep_pr_tiago',
    'bom jardim da serra (sc)': 'rep_pr_tiago',
    'bom jesus (sc)': 'rep_pr_jefferson',
    'bom jesus do oeste (sc)': 'rep_pr_jefferson',
    'bom retiro (sc)': 'rep_pr_tiago',
    'bombinhas (sc)': 'rep_pr_tiago',
    'botuverá (sc)': 'rep_pr_tiago',
    'braço do norte (sc)': 'rep_pr_tiago',
    'braço do trombudo (sc)': 'rep_pr_tiago',
    'brunópolis (sc)': 'rep_pr_tiago',
    'brusque (sc)': 'rep_pr_tiago',
    'caçador (sc)': 'rep_pr_tiago',
    'caibi (sc)': 'rep_pr_jefferson',
    'calmon (sc)': 'rep_pr_tiago',
    'camboriú (sc)': 'rep_pr_tiago',
    'campo alegre (sc)': 'rep_pr_tiago',
    'campo belo do sul (sc)': 'rep_pr_tiago',
    'campo ere (sc)': 'rep_pr_jefferson',
    'campos novos (sc)': 'rep_pr_tiago',
    'canelinha (sc)': 'rep_pr_tiago',
    'canoinhas (sc)': 'rep_pr_tiago',
    'capão alto (sc)': 'rep_pr_tiago',
    'capinzal (sc)': 'rep_pr_tiago',
    'capivari de baixo (sc)': 'rep_pr_tiago',
    'catanduvas (sc)': 'rep_pr_tiago',
    'caxambu do sul (sc)': 'rep_pr_jefferson',
    'celso ramos (sc)': 'rep_pr_tiago',
    'cerro negro (sc)': 'rep_pr_tiago',
    'chapadão do lageado (sc)': 'rep_pr_tiago',
    'chapecó (sc)': 'rep_pr_jefferson',
    'cocal do sul (sc)': 'rep_pr_tiago',
    'concórdia (sc)': 'rep_pr_jefferson',
    'cordilheira alta (sc)': 'rep_pr_jefferson',
    'coronel freitas (sc)': 'rep_pr_jefferson',
    'coronel martins (sc)': 'rep_pr_jefferson',
    'correia pinto (sc)': 'rep_pr_tiago',
    'corupá (sc)': 'rep_pr_tiago',
    'criciúma (sc)': 'rep_pr_tiago',
    'cunha porã (sc)': 'rep_pr_jefferson',
    'cunhatal (sc)': 'rep_pr_jefferson',
    'curitibanos (sc)': 'rep_pr_tiago',
    'descanso (sc)': 'rep_pr_jefferson',
    'dionísio cerqueira (sc)': 'rep_pr_jefferson',
    'dona emma (sc)': 'rep_pr_tiago',
    'doutor pedrinho (sc)': 'rep_pr_tiago',
    'entre rios (sc)': 'rep_pr_jefferson',
    'ermo (sc)': 'rep_pr_tiago',
    'erval velho (sc)': 'rep_pr_tiago',
    'faxinal dos guedes (sc)': 'rep_pr_jefferson',
    'flor do sertão (sc)': 'rep_pr_jefferson',
    'florianópolis (sc)': 'rep_pr_tiago',
    'formosa do sul (sc)': 'rep_pr_jefferson',
    'forquilhinha (sc)': 'rep_pr_tiago',
    'fraiburgo (sc)': 'rep_pr_tiago',
    'frei rogério (sc)': 'rep_pr_tiago',
    'galvão (sc)': 'rep_pr_jefferson',
    'garopaba (sc)': 'rep_pr_tiago',
    'garuva (sc)': 'rep_pr_tiago',
    'gaspar (sc)': 'rep_pr_tiago',
    'governador celso ramos (sc)': 'rep_pr_tiago',
    'grão pará (sc)': 'rep_pr_tiago',
    'gravatal (sc)': 'rep_pr_tiago',
    'guabiruba (sc)': 'rep_pr_tiago',
    'guaraciaba (sc)': 'rep_pr_jefferson',
    'guaramirim (sc)': 'rep_pr_tiago',
    'guarujá do sul (sc)': 'rep_pr_jefferson',
    'guatambu (sc)': 'rep_pr_jefferson',
    'herval d\'oeste (sc)': 'rep_pr_tiago',
    'ibiam (sc)': 'rep_pr_tiago',
    'ibicaré (sc)': 'rep_pr_tiago',
    'ibirama (sc)': 'rep_pr_tiago',
    'içara (sc)': 'rep_pr_tiago',
    'ilhota (sc)': 'rep_pr_tiago',
    'imaruí (sc)': 'rep_pr_tiago',
    'imbituba (sc)': 'rep_pr_tiago',
    'imbuia (sc)': 'rep_pr_tiago',
    'indaial (sc)': 'rep_pr_tiago',
    'iomerê (sc)': 'rep_pr_tiago',
    'ipira (sc)': 'rep_pr_jefferson',
    'iporã do oeste (sc)': 'rep_pr_jefferson',
    'ipuaçu (sc)': 'rep_pr_jefferson',
    'ipumirim (sc)': 'rep_pr_jefferson',
    'iraceminha (sc)': 'rep_pr_jefferson',
    'irani (sc)': 'rep_pr_jefferson',
    'irati (sc)': 'rep_pr_jefferson',
    'irineópolis (sc)': 'rep_pr_tiago',
    'itá (sc)': 'rep_pr_jefferson',
    'itaiópolis (sc)': 'rep_pr_tiago',
    'itajaí (sc)': 'rep_pr_tiago',
    'itapema (sc)': 'rep_pr_tiago',
    'itapiranga (sc)': 'rep_pr_jefferson',
    'itapoá (sc)': 'rep_pr_tiago',
    'ituporanga (sc)': 'rep_pr_tiago',
    'jabora (sc)': 'rep_pr_jefferson',
    'jacinto machado (sc)': 'rep_pr_tiago',
    'jaguaruna (sc)': 'rep_pr_tiago',
    'jaraguá do sul (sc)': 'rep_pr_tiago',
    'jardinópolis (sc)': 'rep_pr_jefferson',
    'joaçaba (sc)': 'rep_pr_tiago',
    'joinville (sc)': 'rep_pr_tiago',
    'josé boiteux (sc)': 'rep_pr_tiago',
    'jupiá (sc)': 'rep_pr_jefferson',
    'lacerdópolis (sc)': 'rep_pr_tiago',
    'lages (sc)': 'rep_pr_tiago',
    'laguna (sc)': 'rep_pr_tiago',
    'lajeado grande (sc)': 'rep_pr_jefferson',
    'laurentino (sc)': 'rep_pr_tiago',
    'lauro muller (sc)': 'rep_pr_tiago',
    'lebon régis (sc)': 'rep_pr_tiago',
    'leoberto leal (sc)': 'rep_pr_tiago',
    'lindoia do sul (sc)': 'rep_pr_jefferson',
    'lontras (sc)': 'rep_pr_tiago',
    'luiz alves (sc)': 'rep_pr_tiago',
    'luzerna (sc)': 'rep_pr_tiago',
    'macieira (sc)': 'rep_pr_tiago',
    'mafra (sc)': 'rep_pr_tiago',
    'major gercino (sc)': 'rep_pr_tiago',
    'major vieira (sc)': 'rep_pr_tiago',
    'maracajá (sc)': 'rep_pr_tiago',
    'maravilha (sc)': 'rep_pr_jefferson',
    'marema (sc)': 'rep_pr_jefferson',
    'massaranduba (sc)': 'rep_pr_tiago',
    'matos costa (sc)': 'rep_pr_tiago',
    'meleiro (sc)': 'rep_pr_tiago',
    'mirim doce (sc)': 'rep_pr_tiago',
    'modelo (sc)': 'rep_pr_jefferson',
    'mondaí (sc)': 'rep_pr_jefferson',
    'monte carlo (sc)': 'rep_pr_tiago',
    'monte castelo (sc)': 'rep_pr_tiago',
    'morro da fumaça (sc)': 'rep_pr_tiago',
    'morro grande (sc)': 'rep_pr_tiago',
    'navegantes (sc)': 'rep_pr_tiago',
    'nova erechim (sc)': 'rep_pr_jefferson',
    'nova itaberaba (sc)': 'rep_pr_jefferson',
    'nova trento (sc)': 'rep_pr_tiago',
    'nova veneza (sc)': 'rep_pr_tiago',
    'novo horizonte (sc)': 'rep_pr_jefferson',
    'orleans (sc)': 'rep_pr_tiago',
    'otacílio costa (sc)': 'rep_pr_tiago',
    'ouro (sc)': 'rep_pr_tiago',
    'ouro verde (sc)': 'rep_pr_jefferson',
    'paial (sc)': 'rep_pr_jefferson',
    'painel (sc)': 'rep_pr_tiago',
    'palhoça (sc)': 'rep_pr_tiago',
    'palma sola (sc)': 'rep_pr_jefferson',
    'palmeira (sc)': 'rep_pr_tiago',
    'palmitos (sc)': 'rep_pr_jefferson',
    'papanduva (sc)': 'rep_pr_tiago',
    'paraíso (sc)': 'rep_pr_jefferson',
    'passo de torres (sc)': 'rep_pr_tiago',
    'passos maia (sc)': 'rep_pr_jefferson',
    'paulo lopes (sc)': 'rep_pr_tiago',
    'pedras grandes (sc)': 'rep_pr_tiago',
    'penha (sc)': 'rep_pr_tiago',
    'peritiba (sc)': 'rep_pr_jefferson',
    'pescaria brava (sc)': 'rep_pr_tiago',
    'petrolândia (sc)': 'rep_pr_tiago',
    'piçarras (sc)': 'rep_pr_jefferson',
    'pinhalzinho (sc)': 'rep_pr_jefferson',
    'pinheiro preto (sc)': 'rep_pr_tiago',
    'piratuba (sc)': 'rep_pr_jefferson',
    'planalto alegre (sc)': 'rep_pr_jefferson',
    'pomerode (sc)': 'rep_pr_tiago',
    'ponte alta (sc)': 'rep_pr_tiago',
    'ponte alta do norte (sc)': 'rep_pr_tiago',
    'ponte serrada (sc)': 'rep_pr_jefferson',
    'porto belo (sc)': 'rep_pr_tiago',
    'porto união (sc)': 'rep_pr_tiago',
    'pouso redondo (sc)': 'rep_pr_tiago',
    'praia grande (sc)': 'rep_pr_tiago',
    'presidente castelo branco (sc)': 'rep_pr_jefferson',
    'presidente getúlio (sc)': 'rep_pr_tiago',
    'presidente nereu (sc)': 'rep_pr_tiago',
    'princesa (sc)': 'rep_pr_jefferson',
    'quilombo (sc)': 'rep_pr_jefferson',
    'rancho queimado (sc)': 'rep_pr_tiago',
    'rio das antas (sc)': 'rep_pr_tiago',
    'rio do campo (sc)': 'rep_pr_tiago',
    'rio do oeste (sc)': 'rep_pr_tiago',
    'rio do sul (sc)': 'rep_pr_tiago',
    'rio dos cedros (sc)': 'rep_pr_tiago',
    'rio fortuna (sc)': 'rep_pr_tiago',
    'rio negrinho (sc)': 'rep_pr_tiago',
    'rio rufino (sc)': 'rep_pr_tiago',
    'riqueza (sc)': 'rep_pr_jefferson',
    'rodeio (sc)': 'rep_pr_tiago',
    'romelandia (sc)': 'rep_pr_jefferson',
    'salete (sc)': 'rep_pr_tiago',
    'saltinho (sc)': 'rep_pr_jefferson',
    'salto veloso (sc)': 'rep_pr_tiago',
    'sangão (sc)': 'rep_pr_tiago',
    'santa cecília (sc)': 'rep_pr_tiago',
    'santa helena (sc)': 'rep_pr_jefferson',
    'santa rosa de lima (sc)': 'rep_pr_tiago',
    'santa rosa do sul (sc)': 'rep_pr_tiago',
    'santa terezinha (sc)': 'rep_pr_tiago',
    'santa terezinha do progresso (sc)': 'rep_pr_tiago',
    'santiago do sul (sc)': 'rep_pr_jefferson',
    'santo amaro da imperatriz (sc)': 'rep_pr_tiago',
    'são bento do sul (sc)': 'rep_pr_tiago',
    'são bernardino (sc)': 'rep_pr_jefferson',
    'são bonifácio (sc)': 'rep_pr_tiago',
    'são carlos (sc)': 'rep_pr_jefferson',
    'são cristovão do sul (sc)': 'rep_pr_tiago',
    'são domingos (sc)': 'rep_pr_jefferson',
    'são francisco do sul (sc)': 'rep_pr_tiago',
    'são joão batista (sc)': 'rep_pr_tiago',
    'são joão do itaperiú (sc)': 'rep_pr_tiago',
    'são joao do oeste (sc)': 'rep_pr_jefferson',
    'são joão do sul (sc)': 'rep_pr_tiago',
    'são joaquim (sc)': 'rep_pr_tiago',
    'são josé (sc)': 'rep_pr_tiago',
    'são jose do cedro (sc)': 'rep_pr_jefferson',
    'são josé do cerrito (sc)': 'rep_pr_tiago',
    'são lourenço do oeste (sc)': 'rep_pr_jefferson',
    'são ludgero (sc)': 'rep_pr_tiago',
    'são martinho (sc)': 'rep_pr_tiago',
    'são miguel da boa vista (sc)': 'rep_pr_jefferson',
    'são miguel do oeste (sc)': 'rep_pr_jefferson',
    'são pedro de alcântara (sc)': 'rep_pr_tiago',
    'saudades (sc)': 'rep_pr_jefferson',
    'schroeder (sc)': 'rep_pr_tiago',
    'seara (sc)': 'rep_pr_jefferson',
    'serra alta (sc)': 'rep_pr_jefferson',
    'siderópolis (sc)': 'rep_pr_tiago',
    'sombrio (sc)': 'rep_pr_tiago',
    'sul brasil (sc)': 'rep_pr_jefferson',
    'taió (sc)': 'rep_pr_tiago',
    'tangarÁ (sc)': 'rep_pr_tiago',
    'tigrinhos (sc)': 'rep_pr_jefferson',
    'tijucas (sc)': 'rep_pr_tiago',
    'timbé do sul (sc)': 'rep_pr_tiago',
    'timbó (sc)': 'rep_pr_tiago',
    'timbó grande (sc)': 'rep_pr_tiago',
    'três barras (sc)': 'rep_pr_tiago',
    'treviso (sc)': 'rep_pr_tiago',
    'treze de maio (sc)': 'rep_pr_tiago',
    'treze tílias (sc)': 'rep_pr_tiago',
    'trombudo central (sc)': 'rep_pr_tiago',
    'tubarão (sc)': 'rep_pr_tiago',
    'tunapolis (sc)': 'rep_pr_jefferson',
    'turvo (sc)': 'rep_pr_tiago',
    'união do oeste (sc)': 'rep_pr_jefferson',
    'urubici (sc)': 'rep_pr_tiago',
    'urupema (sc)': 'rep_pr_tiago',
    'urussanga (sc)': 'rep_pr_tiago',
    'vargeao (sc)': 'rep_pr_jefferson',
    'vargem (sc)': 'rep_pr_tiago',
    'vargem bonita (sc)': 'rep_pr_tiago',
    'vidal ramos (sc)': 'rep_pr_tiago',
    'videira (sc)': 'rep_pr_tiago',
    'vitor meireles (sc)': 'rep_pr_tiago',
    'witmarsum (sc)': 'rep_pr_tiago',
    'xanxere (sc)': 'rep_pr_jefferson',
    'xavantina (sc)': 'rep_pr_jefferson',
    'xaxim (sc)': 'rep_pr_jefferson',
    'zortéa (sc)': 'rep_pr_tiago',

    // --- Rio Grande do Sul (RS) - ATUALIZADO ---
    'aceguá (rs)': 'rep_rs_bortolan',
    'água santa (rs)': 'rep_rs_bortolan',
    'agudo (rs)': 'rep_rs_bortolan',
    'ajuricaba (rs)': 'rep_rs_bortolan',
    'alecrim (rs)': 'rep_rs_bortolan',
    'alegrete (rs)': 'rep_rs_bortolan',
    'alegria (rs)': 'rep_rs_bortolan',
    'almirante tamandaré do sul (rs)': 'rep_rs_bortolan',
    'alpestre (rs)': 'rep_rs_bortolan',
    'alto alegre (rs)': 'rep_rs_bortolan',
    'alto feliz (rs)': 'rep_rs_bortolan',
    'alvorada (rs)': 'rep_rs_bortolan',
    'amaral ferrador (rs)': 'rep_rs_bortolan',
    'ametista do sul (rs)': 'rep_rs_bortolan',
    'andré da rocha (rs)': 'rep_rs_bortolan',
    'anta gorda (rs)': 'rep_rs_bortolan',
    'antônio prado (rs)': 'rep_rs_bortolan',
    'arambaré (rs)': 'rep_rs_bortolan',
    'araricá (rs)': 'rep_rs_bortolan',
    'aratiba (rs)': 'rep_rs_bortolan',
    'arroio do meio (rs)': 'rep_rs_bortolan',
    'arroio do padre (rs)': 'rep_rs_bortolan',
    'arroio do sal (rs)': 'rep_rs_bortolan',
    'arroio do tigre (rs)': 'rep_rs_bortolan',
    'arroio dos ratos (rs)': 'rep_rs_bortolan',
    'arroio grande (rs)': 'rep_rs_bortolan',
    'arvorezinha (rs)': 'rep_rs_bortolan',
    'augusto pestana (rs)': 'rep_rs_bortolan',
    'áurea (rs)': 'rep_rs_bortolan',
    'bagé (rs)': 'rep_rs_bortolan',
    'balneário pinhal (rs)': 'rep_rs_bortolan',
    'barão (rs)': 'rep_rs_bortolan',
    'barão de cotegipe (rs)': 'rep_rs_bortolan',
    'barão do triunfo (rs)': 'rep_rs_bortolan',
    'barra do guarita (rs)': 'rep_rs_bortolan',
    'barra do quaraí (rs)': 'rep_rs_bortolan',
    'barra do ribeiro (rs)': 'rep_rs_bortolan',
    'barra do rio azul (rs)': 'rep_rs_bortolan',
    'barra funda (rs)': 'rep_rs_bortolan',
    'barracão (rs)': 'rep_rs_bortolan',
    'barros cassal (rs)': 'rep_rs_bortolan',
    'benjamin constant do sul (rs)': 'rep_rs_bortolan',
    'bento gonçalves (rs)': 'rep_rs_bortolan',
    'boa vista das missões (rs)': 'rep_rs_bortolan',
    'boa vista do buricá (rs)': 'rep_rs_bortolan',
    'boa vista do cadeado (rs)': 'rep_rs_bortolan',
    'boa vista do incra (rs)': 'rep_rs_bortolan',
    'boa vista do sul (rs)': 'rep_rs_bortolan',
    'bom jesus (rs)': 'rep_rs_bortolan',
    'bom princípio (rs)': 'rep_rs_bortolan',
    'bom progresso (rs)': 'rep_rs_bortolan',
    'bom retiro do sul (rs)': 'rep_rs_bortolan',
    'boqueirão do leão (rs)': 'rep_rs_bortolan',
    'bossoroca (rs)': 'rep_rs_bortolan',
    'bozano (rs)': 'rep_rs_bortolan',
    'braga (rs)': 'rep_rs_bortolan',
    'brochier (rs)': 'rep_rs_bortolan', // Corrigido de BROQUIER
    'butiá (rs)': 'rep_rs_bortolan',
    'caçapava do sul (rs)': 'rep_rs_bortolan',
    'cacequi (rs)': 'rep_rs_bortolan',
    'cachoeira do sul (rs)': 'rep_rs_bortolan',
    'cachoeirinha (rs)': 'rep_rs_bortolan',
    'cacique doble (rs)': 'rep_rs_bortolan',
    'caibaté (rs)': 'rep_rs_bortolan',
    'caiçara (rs)': 'rep_rs_bortolan',
    'camaquã (rs)': 'rep_rs_bortolan',
    'camargo (rs)': 'rep_rs_bortolan',
    'cambará do sul (rs)': 'rep_rs_bortolan',
    'campestre da serra (rs)': 'rep_rs_bortolan',
    'campina das missões (rs)': 'rep_rs_bortolan',
    'campinas do sul (rs)': 'rep_rs_bortolan',
    'campo bom (rs)': 'rep_rs_bortolan',
    'campo novo (rs)': 'rep_rs_bortolan',
    'campos borges (rs)': 'rep_rs_bortolan',
    'candelária (rs)': 'rep_rs_bortolan',
    'cândido godói (rs)': 'rep_rs_bortolan',
    'candiota (rs)': 'rep_rs_bortolan',
    'canela (rs)': 'rep_rs_bortolan',
    'canguçu (rs)': 'rep_rs_bortolan',
    'canoas (rs)': 'rep_rs_bortolan',
    'canudos do vale (rs)': 'rep_rs_bortolan',
    'capão bonito do sul (rs)': 'rep_rs_bortolan',
    'capão da canoa (rs)': 'rep_rs_bortolan',
    'capão do cipó (rs)': 'rep_rs_bortolan',
    'capão do leão (rs)': 'rep_rs_bortolan',
    'capela de santana (rs)': 'rep_rs_bortolan',
    'capitão (rs)': 'rep_rs_bortolan',
    'capivari do sul (rs)': 'rep_rs_bortolan',
    'caraá (rs)': 'rep_rs_bortolan',
    'carazinho (rs)': 'rep_rs_bortolan',
    'carlos barbosa (rs)': 'rep_rs_bortolan',
    'carlos gomes (rs)': 'rep_rs_bortolan',
    'casca (rs)': 'rep_rs_bortolan',
    'caseiros (rs)': 'rep_rs_bortolan',
    'catuípe (rs)': 'rep_rs_bortolan',
    'caxias do sul (rs)': 'rep_rs_bortolan',
    'centenário (rs)': 'rep_rs_bortolan',
    'cerrito (rs)': 'rep_rs_bortolan',
    'cerro branco (rs)': 'rep_rs_bortolan',
    'cerro grande (rs)': 'rep_rs_bortolan',
    'cerro grande do sul (rs)': 'rep_rs_bortolan',
    'cerro largo (rs)': 'rep_rs_bortolan',
    'chapada (rs)': 'rep_rs_bortolan',
    'charqueadas (rs)': 'rep_rs_bortolan',
    'charrua (rs)': 'rep_rs_bortolan',
    'chiapetta (rs)': 'rep_rs_bortolan',
    'chuí (rs)': 'rep_rs_bortolan',
    'chuvisca (rs)': 'rep_rs_bortolan',
    'cidreira (rs)': 'rep_rs_bortolan',
    'ciríaco (rs)': 'rep_rs_bortolan',
    'colinas (rs)': 'rep_rs_bortolan',
    'colorado (rs)': 'rep_rs_bortolan',
    'condor (rs)': 'rep_rs_bortolan',
    'constantina (rs)': 'rep_rs_bortolan',
    'coqueiro baixo (rs)': 'rep_rs_bortolan',
    'coqueiros do sul (rs)': 'rep_rs_bortolan',
    'coronel barros (rs)': 'rep_rs_bortolan',
    'coronel bicaco (rs)': 'rep_rs_bortolan',
    'coronel pilar (rs)': 'rep_rs_bortolan',
    'cotiporã (rs)': 'rep_rs_bortolan',
    'coxilha (rs)': 'rep_rs_bortolan',
    'crissiumal (rs)': 'rep_rs_bortolan',
    'cristal (rs)': 'rep_rs_bortolan',
    'cristal do sul (rs)': 'rep_rs_bortolan',
    'cruz alta (rs)': 'rep_rs_bortolan',
    'cruzaltense (rs)': 'rep_rs_bortolan',
    'cruzeiro do sul (rs)': 'rep_rs_bortolan',
    'david canabarro (rs)': 'rep_rs_bortolan',
    'derrubadas (rs)': 'rep_rs_bortolan',
    'dezesesis de novembro (rs)': 'rep_rs_bortolan',
    'dilermando de aguiar (rs)': 'rep_rs_bortolan',
    'dois irmãos (rs)': 'rep_rs_bortolan',
    'dois irmãos das missões (rs)': 'rep_rs_bortolan',
    'dois lajeados (rs)': 'rep_rs_bortolan',
    'dom feliciano (rs)': 'rep_rs_bortolan',
    'dom pedrito (rs)': 'rep_rs_bortolan',
    'dom pedro de alcântara (rs)': 'rep_rs_bortolan',
    'dona francisca (rs)': 'rep_rs_bortolan',
    'doutor ricardo (rs)': 'rep_rs_bortolan',
    'doutor maurício cardoso (rs)': 'rep_rs_bortolan',
    'eldorado do sul (rs)': 'rep_rs_bortolan',
    'encantado (rs)': 'rep_rs_bortolan',
    'encruzilhada do sul (rs)': 'rep_rs_bortolan',
    'engenho velho (rs)': 'rep_rs_bortolan',
    'entre-ijuís (rs)': 'rep_rs_bortolan',
    'entre rios do sul (rs)': 'rep_rs_bortolan',
    'erebango (rs)': 'rep_rs_bortolan',
    'erechim (rs)': 'rep_rs_bortolan',
    'ernestina (rs)': 'rep_rs_bortolan',
    'erval grande (rs)': 'rep_rs_bortolan',
    'erval seco (rs)': 'rep_rs_bortolan',
    'esmeralda (rs)': 'rep_rs_bortolan',
    'esperança do sul (rs)': 'rep_rs_bortolan',
    'espumoso (rs)': 'rep_rs_bortolan',
    'estação (rs)': 'rep_rs_bortolan',
    'estância velha (rs)': 'rep_rs_bortolan',
    'esteio (rs)': 'rep_rs_bortolan',
    'estrela (rs)': 'rep_rs_bortolan',
    'estrela velha (rs)': 'rep_rs_bortolan',
    'eugênio de castro (rs)': 'rep_rs_bortolan',
    'fagundes varela (rs)': 'rep_rs_bortolan',
    'farroupilha (rs)': 'rep_rs_bortolan',
    'faxinal do soturno (rs)': 'rep_rs_bortolan',
    'faxinalzinho (rs)': 'rep_rs_bortolan',
    'fazenda vilanova (rs)': 'rep_rs_bortolan',
    'feliz (rs)': 'rep_rs_bortolan',
    'flores da cunha (rs)': 'rep_rs_bortolan',
    'floriano peixoto (rs)': 'rep_rs_bortolan',
    'fontoura xavier (rs)': 'rep_rs_bortolan',
    'formigueiro (rs)': 'rep_rs_bortolan',
    'forquetinha (rs)': 'rep_rs_bortolan',
    'fortaleza dos valos (rs)': 'rep_rs_bortolan',
    'frederico westphalen (rs)': 'rep_rs_bortolan',
    'garibaldi (rs)': 'rep_rs_bortolan',
    'garruchos (rs)': 'rep_rs_bortolan',
    'gaurama (rs)': 'rep_rs_bortolan',
    'general câmara (rs)': 'rep_rs_bortolan',
    'gentil (rs)': 'rep_rs_bortolan',
    'getúlio vargas (rs)': 'rep_rs_bortolan',
    'giruá (rs)': 'rep_rs_bortolan',
    'glorinha (rs)': 'rep_rs_bortolan',
    'gramado (rs)': 'rep_rs_bortolan',
    'gramado dos loureiros (rs)': 'rep_rs_bortolan',
    'gramado xavier (rs)': 'rep_rs_bortolan',
    'gravataí (rs)': 'rep_rs_bortolan',
    'guabiju (rs)': 'rep_rs_bortolan',
    'guaíba (rs)': 'rep_rs_bortolan',
    'guaporé (rs)': 'rep_rs_bortolan',
    'guarani das missões (rs)': 'rep_rs_bortolan',
    'harmonia (rs)': 'rep_rs_bortolan',
    'herval (rs)': 'rep_rs_bortolan',
    'herveiras (rs)': 'rep_rs_bortolan',
    'horizontina (rs)': 'rep_rs_bortolan',
    'hulha negra (rs)': 'rep_rs_bortolan',
    'humaitá (rs)': 'rep_rs_bortolan',
    'ibarama (rs)': 'rep_rs_bortolan',
    'ibiaçá (rs)': 'rep_rs_bortolan',
    'ibiraiaras (rs)': 'rep_rs_bortolan',
    'ibirapuitã (rs)': 'rep_rs_bortolan',
    'ibirubá (rs)': 'rep_rs_bortolan',
    'igrejinha (rs)': 'rep_rs_bortolan',
    'ijuí (rs)': 'rep_rs_bortolan',
    'ilópolis (rs)': 'rep_rs_bortolan',
    'imbé (rs)': 'rep_rs_bortolan',
    'imigrante (rs)': 'rep_rs_bortolan',
    'independência (rs)': 'rep_rs_bortolan',
    'inhacorá (rs)': 'rep_rs_bortolan',
    'ipê (rs)': 'rep_rs_bortolan',
    'ipiranga do sul (rs)': 'rep_rs_bortolan',
    'iraí (rs)': 'rep_rs_bortolan',
    'itaara (rs)': 'rep_rs_bortolan',
    'itacurubi (rs)': 'rep_rs_bortolan',
    'itapuca (rs)': 'rep_rs_bortolan',
    'itaqui (rs)': 'rep_rs_bortolan',
    'itati (rs)': 'rep_rs_bortolan',
    'itatiba do sul (rs)': 'rep_rs_bortolan',
    'ivorá (rs)': 'rep_rs_bortolan',
    'ivoti (rs)': 'rep_rs_bortolan',
    'jaboticaba (rs)': 'rep_rs_bortolan',
    'jacuizinho (rs)': 'rep_rs_bortolan',
    'jacutinga (rs)': 'rep_rs_bortolan',
    'jaguarão (rs)': 'rep_rs_bortolan',
    'jaguari (rs)': 'rep_rs_bortolan',
    'jaquirana (rs)': 'rep_rs_bortolan',
    'jari (rs)': 'rep_rs_bortolan',
    'jóia (rs)': 'rep_rs_bortolan',
    'júlio de castilhos (rs)': 'rep_rs_bortolan',
    'lagoa bonita do sul (rs)': 'rep_rs_bortolan',
    'lagoa dos três cantos (rs)': 'rep_rs_bortolan',
    'lagoa vermelha (rs)': 'rep_rs_bortolan',
    'lagoão (rs)': 'rep_rs_bortolan',
    'lajeado (rs)': 'rep_rs_bortolan',
    'lajeado do bugre (rs)': 'rep_rs_bortolan',
    'lavras do sul (rs)': 'rep_rs_bortolan',
    'liberato salzano (rs)': 'rep_rs_bortolan',
    'lindolfo collor (rs)': 'rep_rs_bortolan',
    'linha nova (rs)': 'rep_rs_bortolan',
    'maçambará (rs)': 'rep_rs_bortolan',
    'machadinho (rs)': 'rep_rs_bortolan',
    'mampituba (rs)': 'rep_rs_bortolan',
    'manoel viana (rs)': 'rep_rs_bortolan',
    'maquiné (rs)': 'rep_rs_bortolan',
    'maratá (rs)': 'rep_rs_bortolan',
    'marau (rs)': 'rep_rs_bortolan',
    'marcelino ramos (rs)': 'rep_rs_bortolan',
    'mariana pimentel (rs)': 'rep_rs_bortolan',
    'mariano moro (rs)': 'rep_rs_bortolan',
    'marques de souza (rs)': 'rep_rs_bortolan',
    'mata (rs)': 'rep_rs_bortolan',
    'mato castelhano (rs)': 'rep_rs_bortolan',
    'mato leitão (rs)': 'rep_rs_bortolan',
    'mato queimado (rs)': 'rep_rs_bortolan',
    'maximiliano de almeida (rs)': 'rep_rs_bortolan',
    'minas do leão (rs)': 'rep_rs_bortolan',
    'miraguaí (rs)': 'rep_rs_bortolan',
    'montauri (rs)': 'rep_rs_bortolan',
    'monte alegre dos campos (rs)': 'rep_rs_bortolan',
    'monte belo do sul (rs)': 'rep_rs_bortolan',
    'montenegro (rs)': 'rep_rs_bortolan',
    'mormaço (rs)': 'rep_rs_bortolan',
    'morrinhos do sul (rs)': 'rep_rs_bortolan',
    'morro redondo (rs)': 'rep_rs_bortolan',
    'morro reuter (rs)': 'rep_rs_bortolan',
    'mostardas (rs)': 'rep_rs_bortolan',
    'muçum (rs)': 'rep_rs_bortolan',
    'muitos capões (rs)': 'rep_rs_bortolan',
    'muliterno (rs)': 'rep_rs_bortolan',
    'não-me-toque (rs)': 'rep_rs_bortolan',
    'nicolau vergueiro (rs)': 'rep_rs_bortolan',
    'nonoai (rs)': 'rep_rs_bortolan',
    'nova alvorada (rs)': 'rep_rs_bortolan',
    'nova araçá (rs)': 'rep_rs_bortolan',
    'nova bassano (rs)': 'rep_rs_bortolan',
    'nova boa vista (rs)': 'rep_rs_bortolan',
    'nova bréscia (rs)': 'rep_rs_bortolan',
    'nova candelária (rs)': 'rep_rs_bortolan',
    'nova esperança do sul (rs)': 'rep_rs_bortolan',
    'nova hartz (rs)': 'rep_rs_bortolan',
    'nova pádua (rs)': 'rep_rs_bortolan',
    'nova palma (rs)': 'rep_rs_bortolan',
    'nova petrópolis (rs)': 'rep_rs_bortolan',
    'nova prata (rs)': 'rep_rs_bortolan',
    'nova ramada (rs)': 'rep_rs_bortolan',
    'nova roma do sul (rs)': 'rep_rs_bortolan',
    'nova santa rita (rs)': 'rep_rs_bortolan',
    'novo barreiro (rs)': 'rep_rs_bortolan',
    'novo hamburgo (rs)': 'rep_rs_bortolan',
    'novo machado (rs)': 'rep_rs_bortolan',
    'novo tiradentes (rs)': 'rep_rs_bortolan',
    'novo xingu (rs)': 'rep_rs_bortolan',
    'novos cabrais (rs)': 'rep_rs_bortolan',
    'osório (rs)': 'rep_rs_bortolan',
    'paim filho (rs)': 'rep_rs_bortolan',
    'palmares do sul (rs)': 'rep_rs_bortolan',
    'palmeira das missões (rs)': 'rep_rs_bortolan',
    'palmitinho (rs)': 'rep_rs_bortolan',
    'panambi (rs)': 'rep_rs_bortolan',
    'pantano grande (rs)': 'rep_rs_bortolan',
    'paraí (rs)': 'rep_rs_bortolan',
    'paraíso do sul (rs)': 'rep_rs_bortolan',
    'pareci novo (rs)': 'rep_rs_bortolan',
    'parobé (rs)': 'rep_rs_bortolan',
    'passa sete (rs)': 'rep_rs_bortolan',
    'passo do sobrado (rs)': 'rep_rs_bortolan',
    'passo fundo (rs)': 'rep_rs_bortolan',
    'paulo bento (rs)': 'rep_rs_bortolan',
    'paverama (rs)': 'rep_rs_bortolan',
    'pedras altas (rs)': 'rep_rs_bortolan',
    'pedro osório (rs)': 'rep_rs_bortolan',
    'pejuçara (rs)': 'rep_rs_bortolan',
    'pelotas (rs)': 'rep_rs_bortolan',
    'picada café (rs)': 'rep_rs_bortolan',
    'pinhal (rs)': 'rep_rs_bortolan',
    'pinhal da serra (rs)': 'rep_rs_bortolan',
    'pinhal grande (rs)': 'rep_rs_bortolan',
    'pinheirinho do vale (rs)': 'rep_rs_bortolan',
    'pinheiro machado (rs)': 'rep_rs_bortolan',
    'pinto bandeira (rs)': 'rep_rs_bortolan',
    'pirapó (rs)': 'rep_rs_bortolan',
    'piratini (rs)': 'rep_rs_bortolan',
    'planalto (rs)': 'rep_rs_bortolan',
    'poço das antas (rs)': 'rep_rs_bortolan',
    'pontão (rs)': 'rep_rs_bortolan',
    'ponte preta (rs)': 'rep_rs_bortolan',
    'portão (rs)': 'rep_rs_bortolan',
    'porto alegre (rs)': 'rep_rs_bortolan',
    'porto lucena (rs)': 'rep_rs_bortolan',
    'porto mauá (rs)': 'rep_rs_bortolan',
    'porto vera cruz (rs)': 'rep_rs_bortolan',
    'porto xavier (rs)': 'rep_rs_bortolan',
    'pouso novo (rs)': 'rep_rs_bortolan',
    'presidente lucena (rs)': 'rep_rs_bortolan',
    'progresso (rs)': 'rep_rs_bortolan',
    'protásio alves (rs)': 'rep_rs_bortolan',
    'putinga (rs)': 'rep_rs_bortolan',
    'quaraí (rs)': 'rep_rs_bortolan',
    'quatro irmãos (rs)': 'rep_rs_bortolan',
    'quevedos (rs)': 'rep_rs_bortolan',
    'quinze de novembro (rs)': 'rep_rs_bortolan',
    'redentora (rs)': 'rep_rs_bortolan',
    'relvado (rs)': 'rep_rs_bortolan',
    'restinga seca (rs)': 'rep_rs_bortolan',
    'rio dos índios (rs)': 'rep_rs_bortolan',
    'rio grande (rs)': 'rep_rs_bortolan',
    'rio pardo (rs)': 'rep_rs_bortolan',
    'riozinho (rs)': 'rep_rs_bortolan',
    'roca sales (rs)': 'rep_rs_bortolan',
    'rodeio bonito (rs)': 'rep_rs_bortolan',
    'rolador (rs)': 'rep_rs_bortolan',
    'rolante (rs)': 'rep_rs_bortolan',
    'ronda alta (rs)': 'rep_rs_bortolan',
    'rondinha (rs)': 'rep_rs_bortolan',
    'roque gonzales (rs)': 'rep_rs_bortolan',
    'rosário do sul (rs)': 'rep_rs_bortolan',
    'sagrada família (rs)': 'rep_rs_bortolan',
    'saldanha marinho (rs)': 'rep_rs_bortolan',
    'salto do jacuí (rs)': 'rep_rs_bortolan',
    'salvador das missões (rs)': 'rep_rs_bortolan',
    'salvador do sul (rs)': 'rep_rs_bortolan',
    'sananduva (rs)': 'rep_rs_bortolan',
    'santa bárbara do sul (rs)': 'rep_rs_bortolan',
    'santa cecília do sul (rs)': 'rep_rs_bortolan',
    'santa clara do sul (rs)': 'rep_rs_bortolan',
    'santa cruz do sul (rs)': 'rep_rs_bortolan',
    'santa margarida do sul (rs)': 'rep_rs_bortolan',
    'santa maria (rs)': 'rep_rs_bortolan',
    'santa maria do herval (rs)': 'rep_rs_bortolan',
    'santa rosa (rs)': 'rep_rs_bortolan',
    'santa tereza (rs)': 'rep_rs_bortolan',
    'santa vitória do palmar (rs)': 'rep_rs_bortolan',
    'santana da boa vista (rs)': 'rep_rs_bortolan',
    'sant\'ana do livramento (rs)': 'rep_rs_bortolan',
    'santiago (rs)': 'rep_rs_bortolan',
    'santo ângelo (rs)': 'rep_rs_bortolan',
    'santo antônio das missões (rs)': 'rep_rs_bortolan',
    'santo antônio do palma (rs)': 'rep_rs_bortolan',
    'santo antônio do planalto (rs)': 'rep_rs_bortolan',
    'santo augusto (rs)': 'rep_rs_bortolan',
    'santo cristo (rs)': 'rep_rs_bortolan',
    'santo expedito do sul (rs)': 'rep_rs_bortolan',
    'são borja (rs)': 'rep_rs_bortolan',
    'são domingos do sul (rs)': 'rep_rs_bortolan',
    'são francisco de assis (rs)': 'rep_rs_bortolan',
    'são francisco de paula (rs)': 'rep_rs_bortolan',
    'são gabriel (rs)': 'rep_rs_bortolan',
    'são jerônimo (rs)': 'rep_rs_bortolan',
    'são joão da urtiga (rs)': 'rep_rs_bortolan',
    'são joão do polêsine (rs)': 'rep_rs_bortolan',
    'são jorge (rs)': 'rep_rs_bortolan',
    'são josé das missões (rs)': 'rep_rs_bortolan',
    'são josé do herval (rs)': 'rep_rs_bortolan',
    'são josé do hortêncio (rs)': 'rep_rs_bortolan',
    'são josé do inhacorá (rs)': 'rep_rs_bortolan',
    'são josé do norte (rs)': 'rep_rs_bortolan',
    'são josé do ouro (rs)': 'rep_rs_bortolan',
    'são josé do sul (rs)': 'rep_rs_bortolan',
    'são josé dos ausentes (rs)': 'rep_rs_bortolan',
    'são leopoldo (rs)': 'rep_rs_bortolan',
    'são lourenço do sul (rs)': 'rep_rs_bortolan',
    'são luiz gonzaga (rs)': 'rep_rs_bortolan',
    'são marcos (rs)': 'rep_rs_bortolan',
    'são martinho (rs)': 'rep_rs_bortolan',
    'são martinho da serra (rs)': 'rep_rs_bortolan',
    'são miguel das missões (rs)': 'rep_rs_bortolan',
    'são nicolau (rs)': 'rep_rs_bortolan',
    'são paulo das missões (rs)': 'rep_rs_bortolan',
    'são pedro da serra (rs)': 'rep_rs_bortolan',
    'são pedro das missões (rs)': 'rep_rs_bortolan',
    'são pedro do butiá (rs)': 'rep_rs_bortolan',
    'são pedro do sul (rs)': 'rep_rs_bortolan',
    'são sebastião do caí (rs)': 'rep_rs_bortolan',
    'são sepé (rs)': 'rep_rs_bortolan',
    'são valentim (rs)': 'rep_rs_bortolan',
    'são valentim do sul (rs)': 'rep_rs_bortolan',
    'são valério do sul (rs)': 'rep_rs_bortolan',
    'são vendelino (rs)': 'rep_rs_bortolan',
    'são vicente do sul (rs)': 'rep_rs_bortolan',
    'sapiranga (rs)': 'rep_rs_bortolan',
    'sapucaia do sul (rs)': 'rep_rs_bortolan',
    'sarandi (rs)': 'rep_rs_bortolan',
    'seberi (rs)': 'rep_rs_bortolan',
    'sede nova (rs)': 'rep_rs_bortolan',
    'segredo (rs)': 'rep_rs_bortolan',
    'selbach (rs)': 'rep_rs_bortolan',
    'senador salgado filho (rs)': 'rep_rs_bortolan',
    'sentinela do sul (rs)': 'rep_rs_bortolan',
    'serafina corrêa (rs)': 'rep_rs_bortolan',
    'sério (rs)': 'rep_rs_bortolan',
    'sertão (rs)': 'rep_rs_bortolan',
    'sertão santana (rs)': 'rep_rs_bortolan',
    'sete de setembro (rs)': 'rep_rs_bortolan',
    'severiano de almeida (rs)': 'rep_rs_bortolan',
    'silveira martins (rs)': 'rep_rs_bortolan',
    'sinimbu (rs)': 'rep_rs_bortolan',
    'sobradinho (rs)': 'rep_rs_bortolan',
    'soledade (rs)': 'rep_rs_bortolan',
    'santo antônio da patrulha (rs)': 'rep_rs_bortolan', // Corrigido
    'tabaí (rs)': 'rep_rs_bortolan',
    'tapejara (rs)': 'rep_rs_bortolan',
    'tapera (rs)': 'rep_rs_bortolan',
    'tapes (rs)': 'rep_rs_bortolan',
    'taquara (rs)': 'rep_rs_bortolan',
    'taquari (rs)': 'rep_rs_bortolan',
    'taquaruçu do sul (rs)': 'rep_rs_bortolan',
    'tavares (rs)': 'rep_rs_bortolan',
    'tenente portela (rs)': 'rep_rs_bortolan',
    'terra de areia (rs)': 'rep_rs_bortolan',
    'teutônia (rs)': 'rep_rs_bortolan',
    'tio hugo (rs)': 'rep_rs_bortolan',
    'tiradentes do sul (rs)': 'rep_rs_bortolan',
    'toropi (rs)': 'rep_rs_bortolan',
    'torres (rs)': 'rep_rs_bortolan',
    'tramandaí (rs)': 'rep_rs_bortolan',
    'travesseiro (rs)': 'rep_rs_bortolan',
    'três arroios (rs)': 'rep_rs_bortolan',
    'três cachoeiras (rs)': 'rep_rs_bortolan',
    'três coroas (rs)': 'rep_rs_bortolan',
    'três de maio (rs)': 'rep_rs_bortolan',
    'três forquilhas (rs)': 'rep_rs_bortolan',
    'três palmeiras (rs)': 'rep_rs_bortolan',
    'três passos (rs)': 'rep_rs_bortolan',
    'trindade do sul (rs)': 'rep_rs_bortolan',
    'triunfo (rs)': 'rep_rs_bortolan',
    'tucunduva (rs)': 'rep_rs_bortolan',
    'tunas (rs)': 'rep_rs_bortolan',
    'tupanci do sul (rs)': 'rep_rs_bortolan',
    'tupanciretã (rs)': 'rep_rs_bortolan',
    'tupandi (rs)': 'rep_rs_bortolan',
    'tuparendi (rs)': 'rep_rs_bortolan',
    'turuçu (rs)': 'rep_rs_bortolan',
    'ubiretama (rs)': 'rep_rs_bortolan',
    'união da serra (rs)': 'rep_rs_bortolan',
    'unistalda (rs)': 'rep_rs_bortolan',
    'uruguaiana (rs)': 'rep_rs_bortolan',
    'vacaria (rs)': 'rep_rs_bortolan',
    'vale do sol (rs)': 'rep_rs_bortolan',
    'vale real (rs)': 'rep_rs_bortolan',
    'vale verde (rs)': 'rep_rs_bortolan',
    'vanini (rs)': 'rep_rs_bortolan',
    'venâncio aires (rs)': 'rep_rs_bortolan',
    'vera cruz (rs)': 'rep_rs_bortolan',
    'veranópolis (rs)': 'rep_rs_bortolan',
    'vespasiano correa (rs)': 'rep_rs_bortolan',
    'viadutos (rs)': 'rep_rs_bortolan',
    'viamão (rs)': 'rep_rs_bortolan',
    'vicente dutra (rs)': 'rep_rs_bortolan',
    'victor graeff (rs)': 'rep_rs_bortolan',
    'vila flores (rs)': 'rep_rs_bortolan',
    'vila langaro (rs)': 'rep_rs_bortolan',
    'vila maria (rs)': 'rep_rs_bortolan',
    'vila nova do sul (rs)': 'rep_rs_bortolan',
    'vista alegre (rs)': 'rep_rs_bortolan',
    'vista alegre do prata (rs)': 'rep_rs_bortolan',
    'vista gaúcha (rs)': 'rep_rs_bortolan',
    'vitória das missões (rs)': 'rep_rs_bortolan',
    'westfália (rs)': 'rep_rs_bortolan',
    'xangri-lá (rs)': 'rep_rs_bortolan',
};


/**
 * NOVO: Lista COMPLETA de municípios por estado.
 * Usada para popular o Select2.
 */
const ALL_MUNICIPIOS_BY_STATE = {
    'PR': [
        'Abatiá (PR)', 'Adrianópolis (PR)', 'Agudos do Sul (PR)', 'Almirante Tamandaré (PR)',
        'Altamira do Paraná (PR)', 'Altania (PR)', 'Alto Paraná (PR)', 'Alto Piquiri (PR)',
        'Altônia (PR)', 'Alvorada do Sul (PR)', 'Amaporã (PR)', 'Ampere (PR)',
        'Anahy (PR)', 'Andirá (PR)', 'Angulo (PR)', 'Antonina (PR)', 'Antônio Olinto (PR)',
        'Apucarana (PR)', 'Arapongas (PR)', 'Arapoti (PR)', 'Arapuã (PR)', 'Araruna (PR)',
        'Araucária (PR)', 'Ariranha do Ivaí (PR)', 'Assaí (PR)', 'Assis Chateaubriand (PR)',
        'Astorga (PR)', 'Atalaia (PR)', 'Balsa Nova (PR)', 'Bandeirantes (PR)', 'Barbosa Ferraz (PR)',
        'Barra do Jacaré (PR)', 'Barracão (PR)', 'Bela Vista da Caroba (PR)', 'Bela Vista do Paraíso (PR)',
        'Bituruna (PR)', 'Boa Esperança (PR)', 'Boa Esperança do Iguaçú (PR)', 'Boa Ventura do São Roque (PR)',
        'Boa Vista da Aparecida (PR)', 'Bocaiúva do Sul (PR)', 'Bom Jesus do Sul (PR)',
        'Bom Sucesso do Sul (PR)', 'Borrazópolis (PR)', 'Braganey (PR)', 'Brasilândia do Sul (PR)',
        'Cafeára (PR)', 'Cafelândia (PR)', 'Cafezal do Sul (PR)', 'Califórnia (PR)', 'Cambará (PR)',
        'Cambé (PR)', 'Cambira (PR)', 'Campina da Lagoa (PR)', 'Campina do Simão (PR)',
        'Campina Grande do Sul (PR)', 'Campo Bonito (PR)', 'Campo do Tenente (PR)', 'Campo Largo (PR)',
        'Campo Magro (PR)', 'Campo Mourão (PR)', 'Cândido de Abreu (PR)', 'Candói (PR)',
        'Cantagalo (PR)', 'Capanema (PR)', 'Capitão Leônidas Marques (PR)', 'Carambeí (PR)',
        'Carlópolis (PR)', 'Cascavel (PR)', 'Castro (PR)', 'Catanduvas (PR)', 'Centenário do Sul (PR)',
        'Cerro Azul (PR)', 'Céu Azul (PR)', 'Chopinzinho (PR)', 'Cianorte (PR)', 'Cidade Gaúcha (PR)',
        'Clevelândia (PR)', 'Colombo (PR)', 'Colorado (PR)', 'Congonhinhas (PR)',
        'Conselheiro Mairinck (PR)', 'Contenda (PR)', 'Corbélia (PR)', 'Cornélio Procópio (PR)',
        'Coronel Domingos Soares (PR)', 'Coronel Vivida (PR)', 'Corumbataí do Sul (PR)',
        'Cruz Machado (PR)', 'Cruzeiro do Iguaçú (PR)', 'Cruzeiro do Oeste (PR)', 'Cruzeiro do Sul (PR)',
        'Cruzmaltina (PR)', 'Curitiba (PR)', 'Curiúva (PR)', 'Diamante do Norte (PR)',
        'Diamante do Oeste (PR)', 'Diamante do Sul (PR)', 'Dois Vizinhos (PR)', 'Douradina (PR)',
        'Doutor Camargo (PR)', 'Doutor Ulysses (PR)', 'Éneas Marques (PR)', 'Engenheiro Beltrão (PR)',
        'Entre Rios do Oeste (PR)', 'Esperança Nova (PR)', 'Espigão Alto do Iguaçu (PR)',
        'Farol (PR)', 'Faxinal (PR)', 'Fazenda Rio Grande (PR)', 'Fênix (PR)', 'Fernandes Pinheiro (PR)',
        'Figueira (PR)', 'Flor da Serra do Sul (PR)', 'Floraí (PR)', 'Floresta (PR)',
        'Florestópolis (PR)', 'Flórida (PR)', 'Formosa do Oeste (PR)', 'Foz do Iguaçu (PR)',
        'Foz do Jordão (PR)', 'Francisco Alves (PR)', 'Francisco Beltrão (PR)', 'General Carneiro (PR)',
        'Godoy Moreira (PR)', 'Goioerê (PR)', 'Goioxim (PR)', 'Grandes Rios (PR)', 'Guaíra (PR)',
        'Guairaçá (PR)', 'Guamiranga (PR)', 'Guapirama (PR)', 'Guaporema (PR)', 'Guaraci (PR)',
        'Guaraniaçu (PR)', 'Guarapuava (PR)', 'Guaraqueçaba (PR)', 'Guaratuba (PR)',
        'Honório Serpa (PR)', 'Ibaiti (PR)', 'Ibema (PR)', 'Ibiporã (PR)', 'Icaraíma (PR)',
        'Iguaraçu (PR)', 'Iguatu (PR)', 'Imbaú (PR)', 'Imbituva (PR)', 'Inácio Martins (PR)',
        'Inajá (PR)', 'Indianópolis (PR)', 'Ipiranga (PR)', 'Iporã (PR)', 'Iracema do Oeste (PR)',
        'Irati (PR)', 'Iretama (PR)', 'Itaguajé (PR)', 'Itaipulândia (PR)', 'Itambaracá (PR)',
        'Itambé (PR)', 'Itapejara do Oeste (PR)', 'Itaperuçu (PR)', 'Itaúna do Sul (PR)',
        'Ivaí (PR)', 'Ivaiporã (PR)', 'Ivaté (PR)', 'Ivatuba (PR)', 'Jaboti (PR)', 'Jacarezinho (PR)',
        'Jaguapitã (PR)', 'Jaguariaíva (PR)', 'Jandaia do Sul (PR)', 'Janiópolis (PR)',
        'Japira (PR)', 'Japurá (PR)', 'Jardim Alegre (PR)', 'Jardim Olinda (PR)', 'Jataizinho (PR)',
        'Jesuítas (PR)', 'Joaquim Távora (PR)', 'Jundiaí do Sul (PR)', 'Juranda (PR)',
        'Jussara (PR)', 'Kaloré (PR)', 'Lapa (PR)', 'Laranjal (PR)', 'Laranjeiras do Sul (PR)',
        'Leópolis (PR)', 'Lidianópolis (PR)', 'Lindoeste (PR)', 'Loanda (PR)', 'Lobato (PR)',
        'Londrina (PR)', 'Luiziana (PR)', 'Lunardelli (PR)', 'Lupionópolis (PR)', 'Mallet (PR)',
        'Mamborê (PR)', 'Mandaguaçu (PR)', 'Mandaguari (PR)', 'Mandirituba (PR)',
        'Manfrinópolis (PR)', 'Mangueirinha (PR)', 'Manoel Ribas (PR)', 'Marechal Cândido Rondon (PR)',
        'Maria Helena (PR)', 'Marialva (PR)', 'Marilândia do Sul (PR)', 'Marilena (PR)',
        'Mariluz (PR)', 'Maringá (PR)', 'Mariópolis (PR)', 'Maripá (PR)', 'Marmeleiro (PR)',
        'Marquinho (PR)', 'Marumbi (PR)', 'Matelândia (PR)', 'Matinhos (PR)', 'Mato Rico (PR)',
        'Mauá da Serra (PR)', 'Medianeira (PR)', 'Mercedes (PR)', 'Mirador (PR)',
        'Miraselva (PR)', 'Missal (PR)', 'Moreira Sales (PR)', 'Morretes (PR)', 'Munhoz de Melo (PR)',
        'Nossa Senhora das Graças (PR)', 'Nova Aliança do Ivaí (PR)', 'Nova América da Colina (PR)',
        'Nova Aurora (PR)', 'Nova Cantu (PR)', 'Nova Esperança (PR)', 'Nova Esperança do Sudoeste (PR)',
        'Nova Fátima (PR)', 'Nova Laranjeiras (PR)', 'Nova Londrina (PR)', 'Nova Olímpia (PR)',
        'Nova Prata do Iguaçú (PR)', 'Nova Santa Bárbara (PR)', 'Nova Santa Rosa (PR)',
        'Nova Tebas (PR)', 'Novo Itacolomi (PR)', 'Ortigueira (PR)', 'Ourizona (PR)',
        'Ouro Verde do Oeste (PR)', 'Paiçandu (PR)', 'Palmas (PR)', 'Palmeira (PR)',
        'Palmital (PR)', 'Palotina (PR)', 'Paraíso do Norte (PR)', 'Paranacity (PR)',
        'Paranaguá (PR)', 'Paranapoema (PR)', 'Paranavaí (PR)', 'Pato Bragado (PR)',
        'Pato Branco (PR)', 'Paula Freitas (PR)', 'Paulo Frontin (PR)', 'Peabiru (PR)',
        'Perobal (PR)', 'Pérola (PR)', 'Pérola do Oeste (PR)', 'Piên (PR)', 'Pinhais (PR)',
        'Pinhal de São Bento (PR)', 'Pinhalão (PR)', 'Pinhão (PR)', 'Pinhao de São Bento (PR)',
        'Piraí do Sul (PR)', 'Piraquara (PR)', 'Pitanga (PR)', 'Pitangueiras (PR)',
        'Planaltina do Paraná (PR)', 'Planalto (PR)', 'Ponta Grossa (PR)', 'Pontal do Paraná (PR)',
        'Porecatu (PR)', 'Porto Amazonas (PR)', 'Porto Barreiro (PR)', 'Porto Rico (PR)',
        'Porto Vitória (PR)', 'Prado Ferreira (PR)', 'Pranchita (PR)', 'Presidente Castelo Branco (PR)',
        'Primeiro de Maio (PR)', 'Prudentópolis (PR)', 'Quarto Centenário (PR)', 'Quatingá (PR)',
        'Quatro Barras (PR)', 'Quatro Pontes (PR)', 'Quedas do Iguaçu (PR)', 'Querência do Norte (PR)',
        'Quinta do Sol (PR)', 'Quitandinha (PR)', 'Ramilândia (PR)', 'Rancho Alegre (PR)',
        'Rancho Alegre D\'Oeste (PR)', 'Realeza (PR)', 'Rebouças (PR)', 'Renascença (PR)',
        'Reserva (PR)', 'Reserva do Iguaçu (PR)', 'Ribeirão Claro (PR)', 'Ribeirão do Pinhal (PR)',
        'Rio Azul (PR)', 'Rio Bom (PR)', 'Rio Bonito do Iguaçu (PR)', 'Rio Branco do Ivaí (PR)',
        'Rio Branco do Sul (PR)', 'Rio Negro (PR)', 'Rolândia (PR)', 'Roncador (PR)',
        'Rondon (PR)', 'Rosário do Ivaí (PR)', 'Sabáudia (PR)', 'Salgado Filho (PR)',
        'Salto do Itararé (PR)', 'Salto do Lontra (PR)', 'Santa Amélia (PR)', 'Santa Cecília do Pavão (PR)',
        'Santa Cruz de Monte Castelo (PR)', 'Santa Fé (PR)', 'Santa Helena (PR)', 'Santa Inês (PR)',
        'Santa Isabel do Ivaí (PR)', 'Santa Izabel do Oeste (PR)', 'Santa Lúcia (PR)',
        'Santa Maria do Oeste (PR)', 'Santa Mariana (PR)', 'Santa Mônica (PR)',
        'Santa Tereza do Oeste (PR)', 'Santa Terezinha de Itaipu (PR)', 'Santana do Itararé (PR)',
        'Santo Antônio da Platina (PR)', 'Santo Antônio do Caiuá (PR)', 'Santo Antônio do Paraíso (PR)',
        'Santo Antônio do Sudoeste (PR)', 'Santo Inácio (PR)', 'São Carlos do Ivaí (PR)',
        'São Jerônimo da Serra (PR)', 'São João (PR)', 'São João do Caiuá (PR)', 'São João do Ivaí (PR)',
        'São João do Triunfo (PR)', 'São Jorge do Ivaí (PR)', 'São Jorge do Oeste (PR)',
        'São Jorge do Patrocínio (PR)', 'São José da Boa Vista (PR)', 'São José das Palmeiras (PR)',
        'São José dos Pinhais (PR)', 'São Manoel do Paraná (PR)', 'São Mateus do Sul (PR)',
        'São Miguel do Iguaçu (PR)', 'São Pedro do Iguaçu (PR)', 'São Pedro do Ivaí (PR)',
        'São Pedro do Paraná (PR)', 'São Sebastião da Amoreira (PR)', 'São Tomé (PR)',
        'Sapopema (PR)', 'Sarandi (PR)', 'Saudades do Iguaçu (PR)', 'Sengés (PR)',
        'Serranópolis do Iguaçu (PR)', 'Sertaneja (PR)', 'Sertanópolis (PR)', 'Siqueira Campos (PR)',
        'Sulinas (PR)', 'Tamarana (PR)', 'Tamboara (PR)', 'Tapejara (PR)', 'Tapira (PR)',
        'Teixeira Soares (PR)', 'Telêmaco Borba (PR)', 'Terra Boa (PR)', 'Terra Rica (PR)',
        'Terra Roxa (PR)', 'Tibagi (PR)', 'Tijucas do Sul (PR)', 'Toledo (PR)', 'Tomazina (PR)',
        'Três Barras do Paraná (PR)', 'Tunas do Paraná (PR)', 'Tuneiras do Oeste (PR)',
        'Tupassi (PR)', 'Turvo (PR)', 'Ubiratã (PR)', 'Umuarama (PR)', 'União da Vitória (PR)',
        'Uniflor (PR)', 'Uraí (PR)', 'Ventania (PR)', 'Vera Cruz do Oeste (PR)', 'Verê (PR)',
        'Vila Alta (PR)', 'Virmond (PR)', 'Vitorino (PR)', 'Wenceslau Bráz (PR)', 'Xambrê (PR)',
    ],
    'SC': [
        'Abdon Batista (SC)',
        'Abelardo Luz (SC)',
        'Agrolândia (SC)',
        'Agronômica (SC)',
        'Água Doce (SC)',
        'Águas Chapeco (SC)',
        'Águas Frias (SC)',
        'Águas Mornas (SC)',
        'Alfredo Wagner (SC)',
        'Alto Bela Vista (SC)',
        'Anchieta (SC)',
        'Angelina (SC)',
        'Anita Garibaldi (SC)',
        'Anitápolis (SC)',
        'Antônio Carlos (SC)',
        'Apiúna (SC)',
        'Arabutã (SC)',
        'Araquari (SC)',
        'Araranguá (SC)',
        'Armazém (SC)',
        'Arroio Trinta (SC)',
        'Arvoredo (SC)',
        'Ascurra (SC)',
        'Atalanta (SC)',
        'Aurora (SC)',
        'Balneário Arroio do Silva (SC)',
        'Balneário Barra do Sul (SC)',
        'Balneário Camboriú (SC)',
        'Balneário Gaivota (SC)',
        'Balneário Rincão (SC)',
        'Bandeirante (SC)',
        'Barra Bonita (SC)',
        'Barra Velha (SC)',
        'Bela Vista do Toldo (SC)',
        'Belmonte (SC)',
        'Benedito Novo (SC)',
        'Biguaçu (SC)',
        'Blumenau (SC)',
        'Bocaina do Sul (SC)',
        'Bom Jardim da Serra (SC)',
        'Bom Jesus (SC)',
        'Bom Jesus do Oeste (SC)',
        'Bom Retiro (SC)',
        'Bombinhas (SC)',
        'Botuverá (SC)',
        'Braço do Norte (SC)',
        'Braço do Trombudo (SC)',
        'Brunópolis (SC)',
        'Brusque (SC)',
        'Caçador (SC)',
        'Caibi (SC)',
        'Calmon (SC)',
        'Camboriú (SC)',
        'Campo Alegre (SC)',
        'Campo Belo do Sul (SC)',
        'Campo Erê (SC)',
        'Campos Novos (SC)',
        'Canelinha (SC)',
        'Canoinhas (SC)',
        'Capão Alto (SC)',
        'Capinzal (SC)',
        'Capivari de Baixo (SC)',
        'Catanduvas (SC)',
        'Caxambu do Sul (SC)',
        'Celso Ramos (SC)',
        'Cerro Negro (SC)',
        'Chapadão do Lageado (SC)',
        'Chapecó (SC)',
        'Cocal do Sul (SC)',
        'Concórdia (SC)',
        'Cordilheira Alta (SC)',
        'Coronel Freitas (SC)',
        'Coronel Martins (SC)',
        'Correia Pinto (SC)',
        'Corupá (SC)',
        'Criciúma (SC)',
        'Cunha Porã (SC)',
        'Cunhataí (SC)',
        'Curitibanos (SC)',
        'Descanso (SC)',
        'Dionísio Cerqueira (SC)',
        'Dona Emma (SC)',
        'Doutor Pedrinho (SC)',
        'Entre Rios (SC)',
        'Ermo (SC)',
        'Erval Velho (SC)',
        'Faxinal dos Guedes (SC)',
        'Flor do Sertão (SC)',
        'Florianópolis (SC)',
        'Formosa do Sul (SC)',
        'Forquilhinha (SC)',
        'Fraiburgo (SC)',
        'Frei Rogério (SC)',
        'Galvão (SC)',
        'Garopaba (SC)',
        'Garuva (SC)',
        'Gaspar (SC)',
        'Governador Celso Ramos (SC)',
        'Grão Pará (SC)',
        'Gravatal (SC)',
        'Guabiruba (SC)',
        'Guaraciaba (SC)',
        'Guaramirim (SC)',
        'Guarujá do Sul (SC)',
        'Guatambu (SC)',
        'Herval d\'Oeste (SC)',
        'Ibiam (SC)',
        'Ibicaré (SC)',
        'Ibirama (SC)',
        'Içara (SC)',
        'Ilhota (SC)',
        'Imaruí (SC)',
        'Imbituba (SC)',
        'Imbuia (SC)',
        'Indaial (SC)',
        'Iomerê (SC)',
        'Ipira (SC)',
        'Iporã do Oeste (SC)',
        'Ipuaçu (SC)',
        'Ipumirim (SC)',
        'Iraceminha (SC)',
        'Irani (SC)',
        'Irati (SC)',
        'Irineópolis (SC)',
        'Itá (SC)',
        'Itaiópolis (SC)',
        'Itajaí (SC)',
        'Itapema (SC)',
        'Itapiranga (SC)',
        'Itapoá (SC)',
        'Ituporanga (SC)',
        'Jabora (SC)',
        'Jacinto Machado (SC)',
        'Jaguaruna (SC)',
        'Jaraguá do Sul (SC)',
        'Jardinópolis (SC)',
        'Joaçaba (SC)',
        'Joinville (SC)',
        'José Boiteux (SC)',
        'Jupiá (SC)',
        'Lacerdópolis (SC)',
        'Lages (SC)',
        'Laguna (SC)',
        'Lajeado Grande (SC)',
        'Laurentino (SC)',
        'Lauro Muller (SC)',
        'Lebon Régis (SC)',
        'Leoberto Leal (SC)',
        'Lindoia do Sul (SC)',
        'Lontras (SC)',
        'Luiz Alves (SC)',
        'Luzerna (SC)',
        'Macieira (SC)',
        'Mafra (SC)',
        'Major Gercino (SC)',
        'Major Vieira (SC)',
        'Maracajá (SC)',
        'Maravilha (SC)',
        'Marema (SC)',
        'Massaranduba (SC)',
        'Matos Costa (SC)',
        'Meleiro (SC)',
        'Mirim Doce (SC)',
        'Modelo (SC)',
        'Mondaí (SC)',
        'Monte Carlo (SC)',
        'Monte Castelo (SC)',
        'Morro da Fumaça (SC)',
        'Morro Grande (SC)',
        'Navegantes (SC)',
        'Nova Erechim (SC)',
        'Nova Itaberaba (SC)',
        'Nova Trento (SC)',
        'Nova Veneza (SC)',
        'Novo Horizonte (SC)',
        'Orleans (SC)',
        'Otacílio Costa (SC)',
        'Ouro (SC)',
        'Ouro Verde (SC)',
        'Paial (SC)',
        'Painel (SC)',
        'Palhoça (SC)',
        'Palma Sola (SC)',
        'Palmeira (SC)',
        'Palmitos (SC)',
        'Papanduva (SC)',
        'Paraíso (SC)',
        'Passo de Torres (SC)',
        'Passos Maia (SC)',
        'Paulo Lopes (SC)',
        'Pedras Grandes (SC)',
        'Penha (SC)',
        'Peritiba (SC)',
        'Pescaria Brava (SC)',
        'Petrolândia (SC)',
        'Piçarras (SC)',
        'Pinhalzinho (SC)',
        'Pinheiro Preto (SC)',
        'Piratuba (SC)',
        'Planalto Alegre (SC)',
        'Pomerode (SC)',
        'Ponte Alta (SC)',
        'Ponte Alta do Norte (SC)',
        'Ponte Serrada (SC)',
        'Porto Belo (SC)',
        'Porto União (SC)',
        'Pouso Redondo (SC)',
        'Praia Grande (SC)',
        'Presidente Castelo Branco (SC)',
        'Presidente Getúlio (SC)',
        'Presidente Nereu (SC)',
        'Princesa (SC)',
        'Quilombo (SC)',
        'Rancho Queimado (SC)',
        'Rio das Antas (SC)',
        'Rio do Campo (SC)',
        'Rio do Oeste (SC)',
        'Rio do Sul (SC)',
        'Rio dos Cedros (SC)',
        'Rio Fortuna (SC)',
        'Rio Negrinho (SC)',
        'Rio Rufino (SC)',
        'Riqueza (SC)',
        'Rodeio (SC)',
        'Romelândia (SC)',
        'Salete (SC)',
        'Saltinho (SC)',
        'Salto Veloso (SC)',
        'Sangão (SC)',
        'Santa Cecília (SC)',
        'Santa Helena (SC)',
        'Santa Rosa de Lima (SC)',
        'Santa Rosa do Sul (SC)',
        'Santa Terezinha (SC)',
        'Santa Terezinha do Progresso (SC)',
        'Santiago do Sul (SC)',
        'Santo Amaro da Imperatriz (SC)',
        'São Bento do Sul (SC)',
        'São Bernardino (SC)',
        'São Bonifácio (SC)',
        'São Carlos (SC)',
        'São Cristovão do Sul (SC)',
        'São Domingos (SC)',
        'São Francisco do Sul (SC)',
        'São João Batista (SC)',
        'São João do Itaperiú (SC)',
        'São João do Oeste (SC)',
        'São João do Sul (SC)',
        'São Joaquim (SC)',
        'São José (SC)',
        'São José do Cedro (SC)',
        'São José do Cerrito (SC)',
        'São Lourenço do Oeste (SC)',
        'São Ludgero (SC)',
        'São Martinho (SC)',
        'São Miguel da Boa Vista (SC)',
        'São Miguel do Oeste (SC)',
        'São Pedro de Alcântara (SC)',
        'Saudades (SC)',
        'Schroeder (SC)',
        'Seara (SC)',
        'Serra Alta (SC)',
        'Siderópolis (SC)',
        'Sombrio (SC)',
        'Sul Brasil (SC)',
        'Taió (SC)',
        'Tangará (SC)',
        'Tigrinhos (SC)',
        'Tijucas (SC)',
        'Timbé do Sul (SC)',
        'Timbó (SC)',
        'Timbó Grande (SC)',
        'Três Barras (SC)',
        'Treviso (SC)',
        'Treze de Maio (SC)',
        'Treze Tílias (SC)',
        'Trombudo Central (SC)',
        'Tubarão (SC)',
        'Tunápolis (SC)',
        'Turvo (SC)',
        'União do Oeste (SC)',
        'Urubici (SC)',
        'Urupema (SC)',
        'Urussanga (SC)',
        'Vargeão (SC)',
        'Vargem (SC)',
        'Vargem Bonita (SC)',
        'Vidal Ramos (SC)',
        'Videira (SC)',
        'Vitor Meireles (SC)',
        'Witmarsum (SC)',
        'Xanxerê (SC)',
        'Xavantina (SC)',
        'Xaxim (SC)',
        'Zortéa (SC)',
    ],
    'RS': [
        // --- RIO GRANDE DO SUL (RS) - ATUALIZADO ---
        'Aceguá (RS)', 'Água Santa (RS)', 'Agudo (RS)', 'Ajuricaba (RS)', 'Alecrim (RS)',
        'Alegrete (RS)', 'Alegria (RS)', 'Almirante Tamandaré do Sul (RS)', 'Alpestre (RS)',
        'Alto Alegre (RS)', 'Alto Feliz (RS)', 'Alvorada (RS)', 'Amaral Ferrador (RS)',
        'Ametista do Sul (RS)', 'André da Rocha (RS)', 'Anta Gorda (RS)', 'Antônio Prado (RS)',
        'Arambaré (RS)', 'Araricá (RS)', 'Aratiba (RS)', 'Arroio do Meio (RS)',
        'Arroio do Padre (RS)', 'Arroio do Sal (RS)', 'Arroio do Tigre (RS)',
        'Arroio dos Ratos (RS)', 'Arroio Grande (RS)', 'Arvorezinha (RS)', 'Augusto Pestana (RS)',
        'Áurea (RS)', 'Bagé (RS)', 'Balneário Pinhal (RS)', 'Barão (RS)', 'Barão de Cotegipe (RS)',
        'Barão do Triunfo (RS)', 'Barra do Guarita (RS)', 'Barra do Quaraí (RS)',
        'Barra do Ribeiro (RS)', 'Barra do Rio Azul (RS)', 'Barra Funda (RS)', 'Barracão (RS)',
        'Barros Cassal (RS)', 'Benjamin Constant do Sul (RS)', 'Bento Gonçalves (RS)',
        'Boa Vista das Missões (RS)', 'Boa Vista do Buricá (RS)', 'Boa Vista do Cadeado (RS)',
        'Boa Vista do Incra (RS)', 'Boa Vista do Sul (RS)', 'Bom Jesus (RS)', 'Bom Princípio (RS)',
        'Bom Progresso (RS)', 'Bom Retiro do Sul (RS)', 'Boqueirão do Leão (RS)', 'Bossoroca (RS)',
        'Bozano (RS)', 'Braga (RS)', 'Brochier (RS)', 'Butiá (RS)', 'Caçapava do Sul (RS)',
        'Cacequi (RS)', 'Cachoeira do Sul (RS)', 'Cachoeirinha (RS)', 'Cacique Doble (RS)',
        'Caibaté (RS)', 'Caiçara (RS)', 'Camaquã (RS)', 'Camargo (RS)', 'Cambará do Sul (RS)',
        'Campestre da Serra (RS)', 'Campina das Missões (RS)', 'Campinas do Sul (RS)',
        'Campo Bom (RS)', 'Campo Novo (RS)', 'Campos Borges (RS)', 'Candelária (RS)',
        'Cândido Godói (RS)', 'Candiota (RS)', 'Canela (RS)', 'Canguçu (RS)', 'Canoas (RS)',
        'Canudos do Vale (RS)', 'Capão Bonito do Sul (RS)', 'Capão da Canoa (RS)',
        'Capão do Cipó (RS)', 'Capão do Leão (RS)', 'Capela de Santana (RS)', 'Capitão (RS)',
        'Capivari do Sul (RS)', 'Caraá (RS)', 'Carazinho (RS)', 'Carlos Barbosa (RS)',
        'Carlos Gomes (RS)', 'Casca (RS)', 'Caseiros (RS)', 'Catuípe (RS)', 'Caxias do Sul (RS)',
        'Centenário (RS)', 'Cerrito (RS)', 'Cerro Branco (RS)', 'Cerro Grande (RS)',
        'Cerro Grande do Sul (RS)', 'Cerro Largo (RS)', 'Chapada (RS)', 'Charqueadas (RS)',
        'Charrua (RS)', 'Chiapetta (RS)', 'Chuí (RS)', 'Chuvisca (RS)', 'Cidreira (RS)',
        'Ciríaco (RS)', 'Colinas (RS)', 'Colorado (RS)', 'Condor (RS)', 'Constantina (RS)',
        'Coqueiro Baixo (RS)', 'Coqueiros do Sul (RS)', 'Coronel Barros (RS)',
        'Coronel Bicaco (RS)', 'Coronel Pilar (RS)', 'Cotiporã (RS)', 'Coxilha (RS)',
        'Crissiumal (RS)', 'Cristal (RS)', 'Cristal do Sul (RS)', 'Cruz Alta (RS)',
        'Cruzaltense (RS)', 'Cruzeiro do Sul (RS)', 'David Canabarro (RS)', 'Derrubadas (RS)',
        'Dezesseis de Novembro (RS)', 'Dilermando de Aguiar (RS)', 'Dois Irmãos (RS)',
        'Dois Irmãos das Missões (RS)', 'Dois Lajeados (RS)', 'Dom Feliciano (RS)',
        'Dom Pedrito (RS)', 'Dom Pedro de Alcântara (RS)', 'Dona Francisca (RS)',
        'Doutor Ricardo (RS)', 'Doutor Maurício Cardoso (RS)', 'Eldorado do Sul (RS)',
        'Encantado (RS)', 'Encruzilhada do Sul (RS)', 'Engenho Velho (RS)', 'Entre-Ijuís (RS)',
        'Entre Rios do Sul (RS)', 'Erebango (RS)', 'Erechim (RS)', 'Ernestina (RS)',
        'Erval Grande (RS)', 'Erval Seco (RS)', 'Esmeralda (RS)', 'Esperança do Sul (RS)',
        'Espumoso (RS)', 'Estação (RS)', 'Estância Velha (RS)', 'Esteio (RS)', 'Estrela (RS)',
        'Estrela Velha (RS)', 'Eugênio de Castro (RS)', 'Fagundes Varela (RS)', 'Farroupilha (RS)',
        'Faxinal do Soturno (RS)', 'Faxinalzinho (RS)', 'Fazenda Vilanova (RS)', 'Feliz (RS)',
        'Flores da Cunha (RS)', 'Floriano Peixoto (RS)', 'Fontoura Xavier (RS)',
        'Formigueiro (RS)', 'Forquetinha (RS)', 'Fortaleza dos Valos (RS)',
        'Frederico Westphalen (RS)', 'Garibaldi (RS)', 'Garruchos (RS)', 'Gaurama (RS)',
        'General Câmara (RS)', 'Gentil (RS)', 'Getúlio Vargas (RS)', 'Giruá (RS)', 'Glorinha (RS)',
        'Gramado (RS)', 'Gramado dos Loureiros (RS)', 'Gramado Xavier (RS)', 'Gravataí (RS)',
        'Guabiju (RS)', 'Guaíba (RS)', 'Guaporé (RS)', 'Guarani das Missões (RS)', 'Harmonia (RS)',
        'Herval (RS)', 'Herveiras (RS)', 'Horizontina (RS)', 'Hulha Negra (RS)', 'Humaitá (RS)',
        'Ibarama (RS)', 'Ibiaçá (RS)', 'Ibiraiaras (RS)', 'Ibirapuitã (RS)', 'Ibirubá (RS)',
        'Igrejinha (RS)', 'Ijuí (RS)', 'Ilópolis (RS)', 'Imbé (RS)', 'Imigrante (RS)',
        'Independência (RS)', 'Inhacorá (RS)', 'Ipê (RS)', 'Ipiranga do Sul (RS)', 'Iraí (RS)',
        'Itaara (RS)', 'Itacurubi (RS)', 'Itapuca (RS)', 'Itaqui (RS)', 'Itati (RS)',
        'Itatiba do Sul (RS)', 'Ivorá (RS)', 'Ivoti (RS)', 'Jaboticaba (RS)', 'Jacuizinho (RS)',
        'Jacutinga (RS)', 'Jaguarão (RS)', 'Jaguari (RS)', 'Jaquirana (RS)', 'Jari (RS)',
        'Jóia (RS)', 'Júlio de Castilhos (RS)', 'Lagoa Bonita do Sul (RS)',
        'Lagoa dos Três Cantos (RS)', 'Lagoa Vermelha (RS)', 'Lagoão (RS)', 'Lajeado (RS)',
        'Lajeado do Bugre (RS)', 'Lavras do Sul (RS)', 'Liberato Salzano (RS)',
        'Lindolfo Collor (RS)', 'Linha Nova (RS)', 'Maçambará (RS)', 'Machadinho (RS)',
        'Mampituba (RS)', 'Manoel Viana (RS)', 'Maquiné (RS)', 'Maratá (RS)', 'Marau (RS)',
        'Marcelino Ramos (RS)', 'Mariana Pimentel (RS)', 'Mariano Moro (RS)',
        'Marques de Souza (RS)', 'Mata (RS)', 'Mato Castelhano (RS)', 'Mato Leitão (RS)',
        'Mato Queimado (RS)', 'Maximiliano de Almeida (RS)', 'Minas do Leão (RS)', 'Miraguaí (RS)',
        'Montauri (RS)', 'Monte Alegre dos Campos (RS)', 'Monte Belo do Sul (RS)',
        'Montenegro (RS)', 'Mormaço (RS)', 'Morrinhos do Sul (RS)', 'Morro Redondo (RS)',
        'Morro Reuter (RS)', 'Mostardas (RS)', 'Muçum (RS)', 'Muitos Capões (RS)',
        'Muliterno (RS)', 'Não-Me-Toque (RS)', 'Nicolau Vergueiro (RS)', 'Nonoai (RS)',
        'Nova Alvorada (RS)', 'Nova Araçá (RS)', 'Nova Bassano (RS)', 'Nova Boa Vista (RS)',
        'Nova Bréscia (RS)', 'Nova Candelária (RS)', 'Nova Esperança do Sul (RS)',
        'Nova Hartz (RS)', 'Nova Pádua (RS)', 'Nova Palma (RS)', 'Nova Petrópolis (RS)',
        'Nova Prata (RS)', 'Nova Ramada (RS)', 'Nova Roma do Sul (RS)', 'Nova Santa Rita (RS)',
        'Novo Barreiro (RS)', 'Novo Hamburgo (RS)', 'Novo Machado (RS)', 'Novo Tiradentes (RS)',
        'Novo Xingu (RS)', 'Novos Cabrais (RS)', 'Osório (RS)', 'Paim Filho (RS)',
        'Palmares do Sul (RS)', 'Palmeira das Missões (RS)', 'Palmitinho (RS)', 'Panambi (RS)',
        'Pantano Grande (RS)', 'Paraí (RS)', 'Paraíso do Sul (RS)', 'Pareci Novo (RS)',
        'Parobé (RS)', 'Passa Sete (RS)', 'Passo do Sobrado (RS)', 'Passo Fundo (RS)',
        'Paulo Bento (RS)', 'Paverama (RS)', 'Pedras Altas (RS)', 'Pedro Osório (RS)',
        'Pejuçara (RS)', 'Pelotas (RS)', 'Picada Café (RS)', 'Pinhal (RS)', 'Pinhal da Serra (RS)',
        'Pinhal Grande (RS)', 'Pinheirinho do Vale (RS)', 'Pinheiro Machado (RS)',
        'Pinto Bandeira (RS)', 'Pirapó (RS)', 'Piratini (RS)', 'Planalto (RS)',
        'Poço das Antas (RS)', 'Pontão (RS)', 'Ponte Preta (RS)', 'Portão (RS)',
        'Porto Alegre (RS)', 'Porto Lucena (RS)', 'Porto Mauá (RS)', 'Porto Vera Cruz (RS)',
        'Porto Xavier (RS)', 'Pouso Novo (RS)', 'Presidente Lucena (RS)', 'Progresso (RS)',
        'Protásio Alves (RS)', 'Putinga (RS)', 'Quaraí (RS)', 'Quatro Irmãos (RS)',
        'Quevedos (RS)', 'Quinze de Novembro (RS)', 'Redentora (RS)', 'Relvado (RS)',
        'Restinga Seca (RS)', 'Rio dos Índios (RS)', 'Rio Grande (RS)', 'Rio Pardo (RS)',
        'Riozinho (RS)', 'Roca Sales (RS)', 'Rodeio Bonito (RS)', 'Rolador (RS)',
        'Rolante (RS)', 'Ronda Alta (RS)', 'Rondinha (RS)', 'Roque Gonzales (RS)',
        'Rosário do Sul (RS)', 'Sagrada Família (RS)', 'Saldanha Marinho (RS)',
        'Salto do Jacuí (RS)', 'Salvador das Missões (RS)', 'Salvador do Sul (RS)',
        'Sananduva (RS)', 'Santa Bárbara do Sul (RS)', 'Santa Cecília do Sul (RS)',
        'Santa Clara do Sul (RS)', 'Santa Cruz do Sul (RS)', 'Santa Margarida do Sul (RS)',
        'Santa Maria (RS)', 'Santa Maria do Herval (RS)', 'Santa Rosa (RS)', 'Santa Tereza (RS)',
        'Santa Vitória do Palmar (RS)', 'Santana da Boa Vista (RS)', 'Sant\'Ana do Livramento (RS)',
        'Santiago (RS)', 'Santo Ângelo (RS)', 'Santo Antônio das Missões (RS)',
        'Santo Antônio do Palma (RS)', 'Santo Antônio do Planalto (RS)', 'Santo Augusto (RS)',
        'Santo Cristo (RS)', 'Santo Expedito do Sul (RS)', 'São Borja (RS)',
        'São Domingos do Sul (RS)', 'São Francisco de Assis (RS)', 'São Francisco de Paula (RS)',
        'São Gabriel (RS)', 'São Jerônimo (RS)', 'São João da Urtiga (RS)',
        'São João do Polêsine (RS)', 'São Jorge (RS)', 'São José das Missões (RS)',
        'São José do Herval (RS)', 'São José do Hortêncio (RS)', 'São José do Inhacorá (RS)',
        'São José do Norte (RS)', 'São José do Ouro (RS)', 'São José do Sul (RS)',
        'São José dos Ausentes (RS)', 'São Leopoldo (RS)', 'São Lourenço do Sul (RS)',
        'São Luiz Gonzaga (RS)', 'São Marcos (RS)', 'São Martinho (RS)',
        'São Martinho da Serra (RS)', 'São Miguel das Missões (RS)', 'São Nicolau (RS)',
        'São Paulo das Missões (RS)', 'São Pedro da Serra (RS)', 'São Pedro das Missões (RS)',
        'São Pedro do Butiá (RS)', 'São Pedro do Sul (RS)', 'São Sebastião do Caí (RS)',
        'São Sepé (RS)', 'São Valentim (RS)', 'São Valentim do Sul (RS)',
        'São Valério do Sul (RS)', 'São Vendelino (RS)', 'São Vicente do Sul (RS)',
        'Sapiranga (RS)', 'Sapucaia do Sul (RS)', 'Sarandi (RS)', 'Seberi (RS)',
        'Sede Nova (RS)', 'Segredo (RS)', 'Selbach (RS)', 'Senador Salgado Filho (RS)',
        'Sentinela do Sul (RS)', 'Serafina Corrêa (RS)', 'Sério (RS)', 'Sertão (RS)',
        'Sertão Santana (RS)', 'Sete de Setembro (RS)', 'Severiano de Almeida (RS)',
        'Silveira Martins (RS)', 'Sinimbu (RS)', 'Sobradinho (RS)', 'Soledade (RS)',
        'Santo Antônio da Patrulha (RS)', 'Tabaí (RS)', 'Tapejara (RS)', 'Tapera (RS)',
        'Tapes (RS)', 'Taquara (RS)', 'Taquari (RS)', 'Taquaruçu do Sul (RS)', 'Tavares (RS)',
        'Tenente Portela (RS)', 'Terra de Areia (RS)', 'Teutônia (RS)', 'Tio Hugo (RS)',
        'Tiradentes do Sul (RS)', 'Toropi (RS)', 'Torres (RS)', 'Tramandaí (RS)',
        'Travesseiro (RS)', 'Três Arroios (RS)', 'Três Cachoeiras (RS)', 'Três Coroas (RS)',
        'Três de Maio (RS)', 'Três Forquilhas (RS)', 'Três Palmeiras (RS)', 'Três Passos (RS)',
        'Trindade do Sul (RS)', 'Triunfo (RS)', 'Tucunduva (RS)', 'Tunas (RS)',
        'Tupanci do Sul (RS)', 'Tupanciretã (RS)', 'Tupandi (RS)', 'Tuparendi (RS)',
        'Turuçu (RS)', 'Ubiretama (RS)', 'Uniã da Serra (RS)', 'Unistalda (RS)',
        'Uruguaiana (RS)', 'Vacaria (RS)', 'Vale do Sol (RS)', 'Vale Real (RS)',
        'Vale Verde (RS)', 'Vanini (RS)', 'Venâncio Aires (RS)', 'Vera Cruz (RS)',
        'Veranópolis (RS)', 'Vespasiano Correa (RS)', 'Viadutos (RS)', 'Viamão (RS)',
        'Vicente Dutra (RS)', 'Victor Graeff (RS)', 'Vila Flores (RS)', 'Vila Lângaro (RS)',
        'Vila Maria (RS)', 'Vila Nova do Sul (RS)', 'Vista Alegre (RS)',
        'Vista Alegre do Prata (RS)', 'Vista Gaúcha (RS)', 'Vitória das Missões (RS)',
        'Westfália (RS)', 'Xangri-Lá (RS)',
    ]
};


// --- VARIÁVEL GLOBAL PARA MAPA NORMALIZADO ---
// Usado pela busca para encontrar o ID do representante
let NORMALIZED_MUNICIPIOS_MAP = {};


// --- 2. FUNÇÕES AUXILIARES ---

/**
 * Normaliza uma string de entrada (remove acentos, minúsculas, etc.).
 */
function normalizeString(str) {
    if (!str) return '';
    return str
        .toLowerCase()
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .trim();
}

/**
 * Constrói o mapa normalizado (sem acentos) para a lógica de busca.
 */
function buildNormalizedMap() {
    const newMap = {};
    for (const key in MUNICIPIOS_MAP) {
        if (MUNICIPIOS_MAP.hasOwnProperty(key)) {
            const normalizedKey = normalizeString(key);
            newMap[normalizedKey] = MUNICIPIOS_MAP[key];
        }
    }
    NORMALIZED_MUNICIPIOS_MAP = newMap;
}

/**
 * Limpa o número de telefone para o link do WhatsApp.
 */
function cleanPhoneNumber(phone) {
    let cleaned = phone.replace(/\D/g, "");
    if (cleaned.length === 11 && !cleaned.startsWith('55')) {
        cleaned = '55' + cleaned;
    } else if (cleaned.length === 10 && !cleaned.startsWith('55')) {
        cleaned = '55' + cleaned;
    }
    return cleaned;
}

/**
 * Popula o dropdown <select> do Select2.
 * LÊ DE "ALL_MUNICIPIOS_BY_STATE".
 */
function populateMunicipiosSelect(selectedEstado) {
    const municipioSelect = $('#municipio-select'); // JQuery selector
    if (!municipioSelect.length) return;

    // 1. Limpa as opções antigas
    municipioSelect.empty();

    // 2. Pega a lista completa de municípios para o estado selecionado
    const municipiosDoEstado = ALL_MUNICIPIOS_BY_STATE[selectedEstado] || [];

    // 3. Formata para o Select2
    const options = municipiosDoEstado.map(municipioKey => {
        return {
            id: municipioKey,
            text: municipioKey
        };
    });

    // 4. Inicializa ou atualiza o Select2 com os novos dados
    municipioSelect.select2({
        data: options,
        placeholder: 'Digite ou selecione seu município...',
        width: '100%',
        theme: 'default'
    });

    // Habilita o dropdown de município
    municipioSelect.prop('disabled', false);
}

/**
 * Limpa os resultados da busca (chamado pelo botão "Fechar").
 */
function fecharResultados() {
    const resultsDiv = document.getElementById('search-results-display');
    if (resultsDiv) {
        resultsDiv.innerHTML = '';
        resultsDiv.className = 'mt-6';
    }
}

// --- 3. FUNÇÃO PRINCIPAL DE BUSCA ---

/**
 * Função principal acionada pelo botão "Buscar Representantes".
 */
function buscarRepresentantes() {
    const estadoSelect = document.getElementById('estado-select');
    const municipioValor = $('#municipio-select').val(); // Pega o valor do Select2
    const resultsDiv = document.getElementById('search-results-display');

    if (!estadoSelect || !resultsDiv) {
        console.error('Elementos do formulário de busca não encontrados.');
        return;
    }

    const estadoValor = estadoSelect.value;

    fecharResultados();
    // Adiciona classes de TEMA ESCURO
    resultsDiv.className = 'mt-6 relative p-4 border rounded-lg shadow-md dark-results-box';

    // --- Validação de Entrada ---
    if (estadoValor === "outros") {
        resultsDiv.innerHTML = `
            <button onclick="fecharResultados()" class="absolute top-2 right-3 text-2xl font-bold close-btn">&times;</button>
            <h3 class="text-xl font-semibold mb-2">Equipe Interna de Vendas</h3>
            <p>Para a sua cidade, por favor, entre em contato diretamente com nossa equipe de vendas Ditrator.</p>
        `;
        return;
    }

    if (!estadoValor || !municipioValor) {
        resultsDiv.className = 'mt-6 relative p-4 border border-red-500 bg-red-900 bg-opacity-30 text-red-200 rounded-lg shadow-md';
        resultsDiv.innerHTML = `
            <button onclick="fecharResultados()" class="absolute top-2 right-3 text-red-300 hover:text-red-100 text-2xl font-bold">&times;</button>
            <p class="font-medium">Por favor, selecione um Estado e um Município para realizar a busca.</p>
        `;
        return;
    }

    // --- LÓGICA DE BUSCA ---

    const chaveBusca = normalizeString(municipioValor);
    const repID = NORMALIZED_MUNICIPIOS_MAP[chaveBusca];
    const representante = repID ? REPRESENTANTES_MAP[repID] : undefined;

    // --- Exibição dos Resultados ---
    if (representante) {
        // Caso: Representante Encontrado
        const telefoneLimpo = cleanPhoneNumber(representante.telefone);
        const whatsappLink = `https://wa.me/${telefoneLimpo}?text=Olá, ${representante.nome.split(' ')[0]}. Encontrei seu contato no site da Ditrator.`;

        resultsDiv.innerHTML = `
            <button onclick="fecharResultados()" class="absolute top-2 right-3 text-2xl font-bold close-btn">&times;</button>
            <h3 class="text-xl font-semibold mb-3">Representante Encontrado:</h3>
            <div class="space-y-2">
                <p><strong>Nome:</strong> ${representante.nome}</p>
                <div class="flex items-center gap-3">
                    <p><strong>Telefone:</strong> ${representante.telefone}</p>
                    <a href="${whatsappLink}" target="_blank" 
                       class="text-green-500 hover:text-green-400 transition-colors duration-200" 
                       title="Abrir no WhatsApp">
                        <i class="fa-brands fa-whatsapp fa-lg"></i>
                    </a>
                </div>
                <p><strong>Email:</strong> ${representante.email}</p>
            </div>
        `;
    } else {
        // Caso: Município não encontrado (cai aqui se a cidade foi omitida - "EM BRANCO")
        resultsDiv.innerHTML = `
            <button onclick="fecharResultados()" class="absolute top-2 right-3 text-2xl font-bold close-btn">&times;</button>
            <h3 class="text-xl font-semibold mb-2">Equipe Interna de Vendas Ditrator</h3>
            <p>Não encontramos um representante específico para <strong>${municipioValor}</strong>.</p>
            <p class="mt-2">Para a sua região, por favor, entre em contato com nossa equipe interna de vendas para assistência.</p>
        `;
    }
}

// --- 4. EVENT LISTENERS (ATUALIZADO PARA JQUERY) ---

$(document).ready(function () {
    // CRIA O MAPA NORMALIZADO AO CARREGAR A PÁGINA
    buildNormalizedMap();

    // Inicializa o Select2 no campo de município (começa desabilitado)
    $('#municipio-select').select2({
        placeholder: 'Primeiro, selecione um Estado...',
        width: '100%',
        theme: 'default'
    });

    // Adiciona o listener para filtrar o <select> de municípios
    $('#estado-select').on('change', function () {
        const estadoValor = $(this).val();

        // Limpa a seleção atual do município
        $('#municipio-select').val(null).trigger('change');

        if (estadoValor && estadoValor !== 'outros') {
            // Popula o Select2 de municípios com base no estado
            populateMunicipiosSelect(estadoValor);
            $('#municipio-select').prop('disabled', false);
        } else {
            // Se for 'outros' ou vazio, desabilita e reseta o placeholder
            $('#municipio-select').empty().select2({
                placeholder: (estadoValor === 'outros') ? 'Selecione "Buscar" para contato' : 'Primeiro, selecione um Estado...',
                width: '100%',
                theme: 'default'
            });
            $('#municipio-select').prop('disabled', true);
        }
    });
});